### ISSUE TITLE
No Sound on ESP32-A1S

### ISSUE THREAD

**Issue by Diddlik** [sle118/squeezelite-esp32#111]
Hello,
I use the board "Squeezelite ESP32-A1S". It worked great with flashing, LMS server is running. Unfortunately, I get no sound, neither from the headphone output, nor speaker connection. I have not done any extra configuration.

**Comment by Diddlik** [comment]
I connected via serialmonitor, than send a new track to esp32, it seems communication is working fine, but without sound.
![grafik](https://user-images.githubusercontent.com/6010713/123777117-2cb83900-d8d0-11eb-8bee-d1587e92f43b.png)

**Comment by sle118** [comment]
These esp-a1s boards have dip switches. I would start with making sure they are configured properly. Other than that, it is critical to Flash the a1s binary, since it is preconfigured for that hardware. You could also visit the forum and see if others have had this before

**Comment by Diddlik** [comment]
I flashed with a1s binary. But could not find any information for dip switches configuration :(

**Comment by philippe44** [comment]
Another user on forum (unless it's you...) is having the same issue with that board and it looks like the board is faulty. Have you tried any other SW to produce sound?

NB: I have one of these boards, I just checked the latest build and it works

**Comment by Diddlik** [comment]
I did the same test and I god the same results...Maybe my board is faulty too. I will test asap wit hnew one.
Thank you
