### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by sozialarbeiter** [sle118/squeezelite-esp32#117]
Hello,

When turning the rotary encoder in 'volume up' direction, I get a core dump. 'volume down' and button press work as expected.
A/DT gpio: 32
B/CLK gpio: 21
SW gpio: 22
Other check boxes left default values.

Many thanks

commit 13294ddd0c9fa8db7db0368b7d96b5265c778406 (HEAD -> master-cmake, tag: build-number-724, origin/master-cmake, origin/HEAD)
Author: Philippe G <philippe44@users.noreply.github.com>
Date:   Tue Oct 5 12:22:46 2021 -0700

[logs.txt](https://github.com/sle118/squeezelite-esp32/files/7332062/logs.txt)

**Comment by philippe44** [comment]
Does it happen in Squeezelite context or only in AirPlay?

**Comment by philippe44** [comment]
Solved
