### ISSUE TITLE
add new display driver gives linking problem

### ISSUE THREAD

**Issue by ponpon1013** [sle118/squeezelite-esp32#130]
Hello,
I try to add new display driver for ILI9486 (it is just an adaptation of ILI9341 driver already implememented).
I create a ILI9486.c file and add ILI9486 reference in display.c file.

I have a problem during link project : "undefined reference to `ILI9486_Detect'"
It 's normal beacause function is defined as external function but I don't understand where I have to add the information to compile my new file and link it.

thank you for your help

**Comment by sle118** [comment]
Could you please provide more details on your build environment?

**Comment by ponpon1013** [comment]
Thank you for your answer,
I work with docker image provided by the git repository to be in ESp-IDF 4.0  and directly in command line with Idf.py build.

I succeed to integrate my file using `idf.py build components/displays`. This produces some errors but after when I launch `idf.py build` it works.

I have some lacks to use cmake and ninja inckude in ESP-idf environment so I don't really kanow what i have done. If somebody has any time to explain me it would be cool.

**Comment by philippe44** [comment]
When you add a C file, you must either use "idf.py reconfigure" or "idf.py fullclean" (I think it's fullclean) or delete the "build" directory so that all *.c files are gobbed. That's probably the reason why your ILI9486 structure was not missing. Otherwise, just do a PR so that we can see what you're doing.

**Comment by ponpon1013** [comment]
Thank you for your answer.
As it is now working with what I have described in my previous message I close the issue and As I  try to add touchscreen module I will open a new issue if your soultion doesn't work.

thank tou again
