### ISSUE TITLE
Equalizer Settings over /jsonrpc.js

### ISSUE THREAD

**Issue by hismastersvoice** [sle118/squeezelite-esp32#132]
Hello Together,

I use the project now since some weeks and I'm really happy with it. Thanks for your great work. 

One thin that I like to do is to set and save the EQ from my control WebUI like with other players eg PiCorePlayer.

I can set the EQ values to the ESP, but can not save it that is available after a reboot of the ESP. 
{"id": 1,"method": "slim.request", "params": ["aa:bb:cc:dd:ee:ff", ["squeezeesp32", "seteq","0,0,0,0,0,0,0,0,0,0"]]}

Is there a way that I also can save the EQ Settings after I have found the right ones? ​

Thanks in advance.

HisMastersVoice

**Comment by andraz213** [comment]
Can you please share what you found out?
