### ISSUE TITLE
How did you compiles the codec libs

### ISSUE THREAD

**Issue by Yohannfra** [sle118/squeezelite-esp32#134]
Hi,

How did you compile the static libraries in **squeezelite-esp32/components/codecs/lib/** ?

Can you share the steps you used ? I'd be happy to make a PR to create a README documentation about it.

Thanks you,

Yohann

**Comment by philippe44** [comment]
It's a manual process for some of them. Some have a "configure" mode and as long as you set GCC and CFLAGS as described at the end of the README, it can compile under Linux using "./configure --host=xtensa". For others, all I have is in the README and the rest is a hack

**Comment by sle118** [comment]
Closing after inactivity
