### ISSUE TITLE
Cannot disable Airplay

### ISSUE THREAD

**Issue by tomlut** [sle118/squeezelite-esp32#150]
`fw: Muse.16.1023.master-cmake, mode: Muse`

I have disabled Airplay, saved and rebooted. 

![Screenshot 2022-06-19 at 10-22-31 lounge-speaker](https://user-images.githubusercontent.com/10679300/174460977-ac8c4ffa-7ca2-4c31-b932-d8261bc060ae.png)

The speaker Airplay service is still available.

**Comment by sle118** [comment]
Could you please try to download the 4.3 binaries from the artefacts and install them, then confirm if this is an issue there?

Thank you

**Comment by tomlut** [comment]
I don't know how or when but this issue seems to have resolved itself.
