### ISSUE TITLE
on master-v4.3 4 bit (16 grayscale levels) displays as 1 bit on SSD1322

### ISSUE THREAD

**Issue by dlbogdan** [sle118/squeezelite-esp32#153]
I've compiled the master-v4.3 with my few custom modifications (need this for Ethernet support) but it seems there's a regression somewhere in the display code as the SSD1322 oled will display only as 1 bit regardless of setting 4 bit or not. 
I've had a look myself at the code but couldn't find anything. 
the nvs var for my display in master-cmake branch that will automatically set the screen to 4 bit is
SPI,width=256,height=64,cs=12,speed=20000000,driver=SSD1322,HFlip,VFlip,rotate

in master-v4.3 branch I even tried to force it by setting :4 on the driver argument to no avail.

**Comment by dlbogdan** [comment]
Any hunch on where in the code to look at least? Just give me a hint and I’ll try to fix this myself.

**Comment by philippe44** [comment]
Are you sure there is an issue here ? I looked at all differences and could not find any change that would make a difference

**Comment by sle118** [comment]
This hasn't moved in over a month. Closing
