### ISSUE TITLE
[Feature Request] Snapcast Support

### ISSUE THREAD

**Issue by herostrat** [sle118/squeezelite-esp32#155]
I know this is a really big feature request and I also know this is really unlikely to be implemented anytime soon, so please see this more of as a collection of resources for interested contributors and myself.

What is [snapcast](https://github.com/badaix/snapcast): 
"Snapcast is a multiroom client-server audio player, where all clients are time synchronized with the server to play perfectly synced audio. It's not a standalone player, but an extension that turns your existing audio player into a Sonos-like multiroom solution.

Currently afaik there are no (stable/useable) snapclient implementation that do not require a full fledged OS (linux, windows).

A discussion in the snapcast repo about a esp32 port:
https://github.com/badaix/snapcast/discussions/599

A working solution (but in my tests not as stable as I wished) is:
https://github.com/jorgenkraghjakobsen/snapclient

ESP-ADF style package of snapclient:
https://github.com/douardda/snapclient-esp-adf

**Comment by sle118** [comment]
I've considered integrating Snapcast in the past but, frankly, it is unlikely to happen for several reasons. One of the biggest challenge right now would be to find room for the extra code; you wouldn't imagine how much we have to scratch our heads right now to keep adding more features, even the simple ones.  The current focus is to get Spotify to work as a stand alone player and it takes quite a bit of space with the C++ libraries and stuff. 

That being said, I doubt either Philippe or myself would find the sort of bandwidth to build something like this, especially when we already have multi room sync from the LMS server.  If someone manages to add this service and want to merge with a pull request, I'll definitely take the time to review the proposition, but until then, I will have to close this issue.

Thank you for suggesting this, though.  I hope someone will stumble on this and find an inspiration!
