### ISSUE TITLE
Audio Input to Speaker and Stream

### ISSUE THREAD

**Issue by AxelJust** [sle118/squeezelite-esp32#158]
As some bords have it Already, The option for Audio Input (I2S or ADC?) would be Great!
To use the A1S AudioKit as an Amp for Turntables or similar.
The next step up would be to use that as source for multiroom as well. Inspierd by a [HifiBerry dokumentation](https://www.hifiberry.com/docs/software/integrate-analoge-audio-devices-into-your-multi-room-system/?utm_campaign=website&utm_source=sendgrid&utm_medium=mail). That might be done by Transmiting a Web radio. Only wondering if it could still be adressed by the LMS stream that would come Back For multiroom.

**Comment by sle118** [comment]
Unfortunately, this would need to be an entirely different project, as the system's architecture wasn't built with that in mind. In addition to that, the system resources are very much at full capacity.
