### ISSUE TITLE
Entering a player name with a space in will cause player to fail

### ISSUE THREAD

**Issue by thomaspreece** [sle118/squeezelite-esp32#16]
The web interface will allow you to put a space in your player name but then doesn't surround that in quotes for the command line so causes the command line to be invalid.

E.g. 
`squeezelite -b 500:2000 -d all=info -n Player NameWithSpace -o I2S`

**Comment by daduke** [comment]
fixed by 71f9f82270ae19b81675c302cff1751210b529b3
