### ISSUE TITLE
WEB UI does not show updated paramaters (i.e. DAC-Options)

### ISSUE THREAD

**Issue by heinerolli** [sle118/squeezelite-esp32#169]
When I try to update DAC Settings via Hardware Tab -> Dac Options:
- If I do not select any from the drop down DACs, the system gives an error and won't save the config (I have a generic PCM5102 I2S DAC, which is not on the dropdown list)
- If I select one of the other dropdown selections (as a dummy entry) and enter Clock, Word and Data GPIOs, the system saves the entries & reboots. But after reboot, the saved entries are not shown.
(I think that this is a WEB interface issue, since I found the correct entries after reboot in the NVS editor page.
Therefor, I just updated directly via NVS Tab and set:
dac-config to 'model=I2S,bck=26,ws=25,do=22')

Also, it would be great if the dropdown could offer an entriy like 'generic I2S DAC', so one does not need to select one of the other ones as a dummy entry.

**Comment by sle118** [comment]
FYI, Philippe and I have made some changes to bring more visibility on errors in the Squeezelite parameters as well as on the UI front where I will ensure that the extra parameters are properly parsed and displayed. Stay tuned

**Comment by sle118** [comment]
going to close this one as I think https://github.com/sle118/squeezelite-esp32/commit/ca7670f754a4562c473a25d28d3d58967fbadace fixed it.
