### ISSUE TITLE
[Feature Request] Add more Bluetooth codecs

### ISSUE THREAD

**Issue by c-OOL-io** [sle118/squeezelite-esp32#174]
As already possible in piCorePlayer, add more BT codecs, like aptX, aptX HD, AAC, etc to the build in BT.

**Comment by sle118** [comment]
I don't mean to disappoint you, but this is very unlikely to happen, unless expressif releases some optimized codec as part of the BT audio support. We are also running very low on available room in flash memory.

PiCorePlayer runs on typically more powerful hardware when compared to the esp32.

**Comment by sle118** [comment]
I'm going to flash @philippe44 to see what he thinks

**Comment by philippe44** [comment]
No, it won't happen

**Comment by c-OOL-io** [comment]
ok, wifi is even better for audio quality then BT. I don't need it on my own, only intereset in home use with multiroom. but thought if possible, interesting for others who are using ESP32 devices also on the go.  ;)
