### ISSUE TITLE
Hardware > DAC Options > DAC Model Name >> I2S is missing

### ISSUE THREAD

**Issue by c-OOL-io** [sle118/squeezelite-esp32#175]
fw: I2S-4MFlash.16.1188.master-v4.3

DAC Model Name >> **I2S** is missing

SInce i'm only got I2S devices I always have to open NVS Editor to change or see my DACs current settings.

In addition the following hardware values do not shop up in GUI, even if there are set/shown in NVS Editor. But maybe related to the main issue that I2S is missing at all.

DAC Options:
- Clock GPIO
- Word Select GPIO
- Data GPIO

**Comment by sle118** [comment]
I think I'll have to admit that's a good find. It's actually puzzling that it's not there in plain sight

**Comment by Renber78** [comment]
the bug is still present in the current version (1501)
