### ISSUE TITLE
Something is wrong with SqeezeESP32 plugin v0.352

### ISSUE THREAD

**Issue by CornelisJ** [sle118/squeezelite-esp32#181]
It seems that something went wrong when the SqueezeESP32 plugin was updated to v0.352. The plugin name has changed on the LMS Plugins tab, and on the Player tab "ESP32 settings" is blanked out. See forum post https://forums.slimdevices.com/showthread.php?112697-ANNOUNCE-Squeezelite-ESP32-(dedicated-thread)&p=1061867&viewfull=1#post1061867 and below. People suggest that something is wrong with line endings in the strings.txt file.

**Comment by philippe44** [comment]
Fixed
