### ISSUE TITLE
esp32-s3

### ISSUE THREAD

**Issue by StuartIanNaylor** [sle118/squeezelite-esp32#194]
Sébastien just curious but with the vector instructions and optimisation of the esp32-s3 have you ever tried any benchmarks on the difference it could make?
Shame there isn't a esp32-s3-a1s maybe with the es7210 4 channel adc and a 2 channel dac than the bloated audio dev kits, but hey :)

**Comment by sle118** [comment]
I haven't tried that chip. I still have many wrover modules lying around. I would be surprised if we spent time on that chip either; the S3 does not support classic Bluetooth, which means no Bluetooth audio streaming!

**Comment by StuartIanNaylor** [comment]
That is ok if you have not. I am not sure it matters that much as the LMS Server only needs a BT5 dongle (not and esspressif one :) ) not the client. I think its a weird decision by Espressif not to support Classic as via the SIG 5.0 is backward compatible but you don't need it at a client if you get what I mean, but maybe they are edging all their bets on AuraCast broadcast audio and much better audio quality codecs than SBR.

I was just curious with with https://docs.espressif.com/projects/esp-dsp/en/latest/esp-dsp-benchmarks.html if the optimised libs where of any use.
