### ISSUE TITLE
ES8388 stereo downmix (register 29)

### ISSUE THREAD

**Issue by pmannk** [sle118/squeezelite-esp32#198]
Hi,
Firstly, thanks for this great project. Absolutely love it!

Could you please consider exposing an option to control Register 29 on the ES8388?
The datasheet indicates register 29, bit 5 can control the stereo/mono behaviour of the DAC.
![image](https://user-images.githubusercontent.com/79073108/202611186-2696bb8f-5941-4ccb-8376-648b2a5e7cb7.png)
If I'm understanding the data sheet correctly this looks like a great way to downmix a mono output, in hardware.

[Linking this old issue for reference in case anyone searches for it.](https://github.com/sle118/squeezelite-esp32/issues/36)
Thankyou.

**Comment by sle118** [comment]
You should try to configure speakeron event of dac_controlset

https://github.com/sle118/squeezelite-esp32#daci2s

**Comment by pmannk** [comment]
Thanks. Have had a couple of unsuccessful attempts. Will keep trying to work it out.

**Comment by sle118** [comment]
For now, I'm concentrating on some stabilizing of release 4.3 and, given we're already short on flash space, is unlikely that we'll be able to implement new features anytime soon.

Hopefully the events should accommodate this. I'll convert this to a conversation instead of an issue
