### ISSUE TITLE
SqueezeAmp PowerSwitch (J7: on/off) causes reboot loop in "off" starting w/ FW 2.1186 and all following 2.x FW versions

### ISSUE THREAD

**Issue by heinerolli** [sle118/squeezelite-esp32#201]
Up to FW 1.1180 the noted power switch of my SqueezeAmp works as expected; but starting w/ FW 2.1186 switching that switch to "off" puts the system into a reboot loop.
Serial-Logs are provided in the forum:
https://forums.slimdevices.com/showthread.php?116788-ANNOUNCE-Squeezelite-ESP32-version-2-x&p=1066247&viewfull=1#post1066247
I tried 16 and 32 bit FW versions up to SqueezeAmp.16.13.master-v4.3: All go into reboot loop.
Going back to FW SqueezeAmp.16.1180.master-cmake makes the switch work again as expected.
This is happening with a std. (very early) SqueezeAmp. Both when using battery or external power. 
Only add-on I use is an OLED display, but the problem occurs also w/o Display and related config.
(Hardwarewise I might have a SqueezeAmp w/ a TI Amp TAS5780 instead of TAS5754 as per communication w/ Philippe44. 
I can not verify due to a glued-on heatsink. 2 years ago I also might have altered the board as per Philippes instructions (see his Github) from 3 battery to 2 battery version and a reduced charging rate, but I am not 100% sure - 
and I can not check w/o risking to break the PCB as it is permanently mounted inside a speaker)
But this should not be a hardware problem as I can consistently fix it by going back to a pre 2.x FW Version (1.1180)

**Comment by heinerolli** [comment]
After further investigation, this seems to be a hardware issue, where the EN Pin on U1 is sensitive to interference.
Using <10cm shielded cable for this switch fixes the problem.
Why FW2.x is more sensotive to this issue than 1.x? I have no clue.

See discussion here:
https://forums.slimdevices.com/showthread.php?116788-ANNOUNCE-Squeezelite-ESP32-version-2-x/page12

**Comment by sle118** [comment]
As discussed, there may be something going on with the new build which makes the system boot even with low voltage. Given that this really comes from a hardware issue, I will go ahead and close it for now. If you make some discoveries, feel free to reopen.
