### ISSUE TITLE
EPS muse - bluetooth speaker not visible

### ISSUE THREAD

**Issue by Elkropac** [sle118/squeezelite-esp32#210]
Hi, i upgraded my espmuse to `fw: Muse.16.2.1241.master-v4.3` and i cannot discover the bluetooth speaker anymore on my phone. It is checked in web interface as enabled

**Comment by sle118** [comment]
This is a duplicate of https://github.com/sle118/squeezelite-esp32/issues/207

Please try the most recent release

**Comment by Elkropac** [comment]
Hi, ok i saw this issue, but i thought it's different problem, he tries to connect to remote BT device

**Comment by Elkropac** [comment]
With 1250 it seems to work, thanks !

**Comment by daduke** [comment]
yes it does! thanks for the quick fix.
