### ISSUE TITLE
LMS playback stuttering

### ISSUE THREAD

**Issue by DL6ER** [sle118/squeezelite-esp32#216]
Thank you for this amazing project.

I set up a bare ESP32-WROVER. I only enabled SPDIF and want to play music from my LMS server. For SPDIF, I connected an LED to the `DO` output and attached this to the SPDIF fiber:

![signal-2022-12-16-190814](https://user-images.githubusercontent.com/16748619/210128496-81ff1330-dcac-4d71-b18e-209edbb03f41.jpeg)

This all works amazingly well for up to about 10 minutes where the audio is getting intermittent and eventually completely breaks. The web interface shows some `timeout` status messages at the same time. WiFi signal is rather good, the ESP32 is located about 2 meters away from the access point. It also happens when I don't have a browser tab opened for the web interface.
A restart of the ESP32 resolves the issue for the next 10 minutes.

**Do you have any suggestions for me what I can try?**

Below is my current configuration:

![Screenshot from 2022-12-31 08-02-45](https://user-images.githubusercontent.com/16748619/210128399-3a689c56-57bd-40f2-98da-91678611fdb0.png)

![Screenshot from 2022-12-31 08-02-25](https://user-images.githubusercontent.com/16748619/210128391-a932cbfc-d96a-4313-a2cd-7882b7507550.png)

![Screenshot from 2022-12-31 08-02-53](https://user-images.githubusercontent.com/16748619/210128394-049a55ab-b880-40dc-baf2-cb9c2b481805.png)

```
fw: I2S-4MFlash.16.2.1254.master-v4, mode: Squeezelite-ESP32
```

**Comment by sle118** [comment]
First thing to do is to connect your device to a USB port and get some logs that you can attach here.

**Comment by andiling** [comment]
Hi, i have the same setup (SPDIF Transmitter on PIN 32) but i have no playback problems! I Use a Toslink transmitter from a ASUS Mainboard. 

fw: I2S-4MFlash.16.2.1254.master-v4, mode: Squeezelite-ESP32

**Comment by sle118** [comment]
@DL6ER given that I don't have logs to figure out what is going on, I cannot help. I'll close this for now. Feel free to reopen to add more details
