### ISSUE TITLE
Muse Luxe Visualiser support

### ISSUE THREAD

**Issue by dekoenpi** [sle118/squeezelite-esp32#219]
Hi all,

Please add visualiser support in squeezelite.

command line working:
squeezelite -b 500:2000 -d all=info -C 30 -W -o I2S -Z 96000 -n "MuseLuxe"
command line not working on muse luxe :
squeezelite -b 500:2000 -d all=info -C 30 -W -o I2S -Z 96000 -n "MuseLuxe" -v

-v | Visualiser support

Best regard
P-Kay

**Comment by sle118** [comment]
What outcome would you expect from activating this flag? I'm not sure I understand

**Comment by dekoenpi** [comment]
This flag is to start squeezelite with visualizer support.

e.g. I want to use cli-visualizer:
https://github.com/dpayne/cli-visualizer#squeezelite-setup

Best regards

**Comment by sle118** [comment]
This is not going to happen. We're already pushing the ESP32 to its limits and there's no way it will be able to support that sort of heavyweight task on top of it all. 

This sort of visualizer is likely better suited for a raspberry Pi or a similar platform.
