### ISSUE TITLE
Power Off button

### ISSUE THREAD

**Issue by wiredcharlie** [sle118/squeezelite-esp32#230]
Whilst amp switching works well with Squeezebox Server it does not always turn off with bluetooth/airplay. I have Squeezebox Power button (ACTRLS_POWER). I suggest that this button should also power off the amp in bluetooth/airplay mode. BTW  - absolutely love your work - thank you!

**Comment by philippe44** [comment]
Not always or never?

**Comment by wiredcharlie** [comment]
It did turn it off once! Nearly never.

**Comment by wiredcharlie** [comment]
Further suggestion - power button does Wake-On-Lan to turn on server?

**Comment by philippe44** [comment]
No

**Comment by sle118** [comment]
@wiredcharlie we have limited development capabilities and our plate is currently full with higher priorities issues/enhancements. For switching on/off amplifiers, there are other solutions available. For example you could consider home assistant.
