### ISSUE TITLE
Opus files with large picture embedded don't play

### ISSUE THREAD

**Issue by robho** [sle118/squeezelite-esp32#243]
I have some opus files which don't play with squeezelite-esp32 (but they do play with "normal" squeezelite).

The output I get is:
```
[12:32:56.726710] output_thread_i2s:463 Output state is 1
[12:32:58.048191] opus_decompress:138 open_callbacks error: -133
[12:32:58.048898] decode_thread:100 decode complete

```

-133 seems to be OP_EBADHEADER.

The problem seems to be large embedded album art. If I remove the album art, then the files play properly.

This is a minor problem to me. If the problem is limited buffers on the esp32, then I have no problem with resizing the album art.

Here's an unplayable opus file:
[01 - Matt Gray - Bangkok Knights Loader.zip](https://github.com/sle118/squeezelite-esp32/files/11132732/01.-.Matt.Gray.-.Bangkok.Knights.Loader.zip)

**Comment by philippe44** [comment]
Congratulations! you've find 2 issues

1- one that impact all squeezelite instances, including the main version (was my own mistake ...)
2- but, that was not enough... on esp32, even the fix does not work as the default opus reader tries to load the whole image in memory, which does not work very well of course

So to solve 2/, I had to remove the entire opusfile wrapper, which is really convenient and provided by opus itself, and use primitive to access to raw stream and skip the "VorbisComment".

Now, there is always something good as getting rid of the opusfile wrapper gained another 7kB of memory and seems to have gained 10% (to be confirmed) of CPU. 

Version is being built as I'm writing this, so please give it a try (not released) but more verifications to be made

PS: I will have to fix the Vorbis code the same way, unfortunately

**Comment by robho** [comment]
Let me know if you want some help testing (a binary would be good then since I don't have a build environment at the moment).

(I have some changes for the AudioScan library that enables seek in opus files, in case you want to test that)

**Comment by philippe44** [comment]
Done for both
