### ISSUE TITLE
Stereo with a bluetooth speaker

### ISSUE THREAD

**Issue by kyvaith** [sle118/squeezelite-esp32#244]
Hi, is it possible to have a wired speaker attached to the board, and at the same time bluetooth speaker connected to make them both work in stereo?

**Comment by sle118** [comment]
If I understand correctly, you would like to know if the software can push audio simultaneously through bluetooth and onboard audio? If so, then no, this is not possible as the ESP32 doesn't have the power that would be required to implement the type of multiplexer this would require.  In addition to this, the delay induced by running the audio stream through the BT codec, then over the air and then through decoding again would be such that the experience would be less than ideal with the speakers being out of phase.

**Comment by kyvaith** [comment]
That's bad. Thanks for answering.
