### ISSUE TITLE
Building from windows, idf v4.0, error with esp_timer

### ISSUE THREAD

**Issue by mph070770** [sle118/squeezelite-esp32#255]
Hi - should we still be using idf v4 for building.  When I use v4, I get the following build error:

Building ESP-IDF components for target esp32
CMake Error at C:/Espressif/frameworks/esp-idf/tools/cmake/build.cmake:187 (message):
  Failed to resolve component 'esp_timer'.
Call Stack (most recent call first):
  C:/Espressif/frameworks/esp-idf/tools/cmake/build.cmake:218 (__build_resolve_and_add_req)
  C:/Espressif/frameworks/esp-idf/tools/cmake/build.cmake:431 (__build_expand_requirements)
  C:/Espressif/frameworks/esp-idf/tools/cmake/project.cmake:352 (idf_build_process)
  CMakeLists.txt:55 (project)

esp_timer seem to be introduced in later builds of idf?

**Comment by sle118** [comment]
You should build using the docker image, as setting up dependencies has grown more complicated than in the early days of the project when the readme section was written. Also please refrain from opening multiple issues on the same topic. Arguably, you wanted some help to build the project yourself and one issue would have been enough.

Thank you for your understanding
