### ISSUE TITLE
Link for ESP32-A1S leads to non existent product

### ISSUE THREAD

**Issue by manherna** [sle118/squeezelite-esp32#263]
Hi! 
The ESP32-A1S Audio Kit board link given as an example in the Docs is not available any more.
Maybe [this one](https://aliexpress.com/item/4000130915903.html) is the same?

**Comment by sle118** [comment]
Your link lands in the DAC chip rather than on the associated board. But yes, it is the board we are referring to

**Comment by manherna** [comment]
Hi @sle118 I created PR #264 to fix this
