### ISSUE TITLE
esp32 audio kit led_brightness usage

### ISSUE THREAD

**Issue by crtvrmn** [sle118/squeezelite-esp32#268]
on my esp32 audio kit i tried to set the value of Led_Brightness to:

- [green=0,red=75]
- [green=0]

and changed 0 to 10, 50 and 100 just out of curiousity. the led is still brighter than the sun, maybe this is not working on the esp32-audio-kit (i read something like this anywhere today in some forum). I rebooted several times after commiting and just put a lot of tape over the led because i saw bright spots when i looked away :D

just wanted to double check if i for some reason misinterpreted the syntax or maybe finally found a but (but well, my guess is its just not working on my hardware)

**Comment by sle118** [comment]
can you share your nvs configuration? it can be downloaded from the UI. Credits/Show NVS Editor will show the tab (or reboot to recovery will show it by default). Then under the NVS Editor tab, at the bottom of the list, there's a download button.

There are several leds on this board. Looking at the schematics, there are 2 which can be controlled: led4, gpio 22 and led5, gpio 19.

**Comment by crtvrmn** [comment]
sure thing. 

did a quick scan through the config and found `  "set_GPIO": "21=amp,22=green:0,39=jack:0",`

seems like i choose the wrong (the older version) of the board, huh? On the board itself is noted its "ESP32 Audio Kit V2.2 A247", originally i choose "Variant 1" (als seen in the config). the button layout seems to change, but the LED (especially the green) is still brighter as the sun; i switched back for now to the config file i posted right now.

(for other people searching: https://github.com/sle118/squeezelite-esp32/issues/123 for aditional info about the ever changing boards)
[nvs_config_TeufelStudio_1689315758936json.txt](https://github.com/sle118/squeezelite-esp32/files/12046903/nvs_config_TeufelStudio_1689315758936json.txt) (i added .txt so i can upload the file instead of copypasting)

btw thanks a lot for reaching out, this is one of the coolest projects i have come across in the past year  <3

**Comment by sle118** [comment]
> btw thanks a lot for reaching out, this is one of the coolest projects i have come across in the past year <3

It is definitely one of the coolest personal project I got involved in. Without @philippe44's support I doubt I would have had the motivation to evolve "my pieces". 

Shall we close this issue, or you need more inputs?

**Comment by crtvrmn** [comment]
my guess right now is, that the led is mapped to the wrong GPIO, and for the same reason not every button is working.
tickles my brain a little bit, is fine with me with the tape - but if you could throw some keywords to guide my search journy it would be much appreciated :)

**Comment by sle118** [comment]
Then you will need some help. I'll keep it open until I can get to this.

If you are familiar with development tools, you could possibly try to run the blink example using your prefered environment, for example Arduino. This isn't too difficult and at least would allow you to identify the correct gpio numbers for the two LEDs that you can control

**Comment by lelithium** [comment]
Chiming in as I have that same exact board, and figured out that green LED.

Resources:
- AI thinker v2.2 schematic https://docs.ai-thinker.com/_media/esp32-audio-kit_v2.2_sch.pdf (not sure which variant that is)
- TP4056 datasheet https://www.analog.com/media/en/technical-documentation/data-sheets/405642f.pdf

There are 5 LEDs total on the board. D1, D2 and D3 are together near the IP4056 charge circuit, alongside the two micro-USB ports, whereas D4 and D5 are on the other side of the board, near the two 3.5mm jacks
- D3 (red) is on as long as there's 3.3V on the board, so permanently.
- D2 (red) and D1 (green) are connected to the IP4056 charge circuit.The schematic shows that the green LED is tied to CHRG, and the red one to STDBY. Unfortunately, that means that as long as no battery is connected, you'll always have the green LED on (and red off)
- D4(red) and D5(red) are tied to IO22 and IO19.

So there's no option it seems to disable that green LED, if you're not using a battery, other than unsoldering it, which is what i"ve done on my board

**Comment by sle118** [comment]
@lelithium thank you for the detailed explanation. Sometimes when I'm just too lazy, I just crush or cut the LEDs :)
