### ISSUE TITLE
Add support for i2c based rotary encoders 

### ISSUE THREAD

**Issue by alidaf** [sle118/squeezelite-esp32#278]
There are a number of i2c based boards available for rotary encoders that would slightly reduce the GPIO count, computational overhead, and avoid the need for debounce circuits. An example is [here](https://learn.adafruit.com/adafruit-i2c-qt-rotary-encoder/arduino).

**Comment by philippe44** [comment]
I guess it requires i2c slave mode which is not included for now. So it's (very) unlikely that I'd add that in the future
