### ISSUE TITLE
idf.py menuconfig fails

### ISSUE THREAD

**Issue by alidaf** [sle118/squeezelite-esp32#283]
I'm running the Docker image and this command fails with CMakeLists.txt not found in project directory.

I'm running the Docker image on a Mac using `docker run -it -v `pwd`:/workspace/squeezelite-esp32 sle118/squeezelite-esp32-idfv435`

**Comment by sle118** [comment]
I am assuming that you've cloned the project locally before attempting to build it? I will move this to the Q&A discussion section. 

Out of curiosity, what is your motivation to build the project instead of using one of the stable builds already available?
