### ISSUE TITLE
Loudness value it not used after a reboot

### ISSUE THREAD

**Issue by christianaubry** [sle118/squeezelite-esp32#301]
First of all congratulation for your great work!

Changing the loudness value to 8 for example and applying does not save it. Both changing in the Audio tab or in the NVS Editor. After a reboot it is back to 0

Using fw: I2S-4MFlash-1532, mode: Squeezelite-ESP32

**Comment by sle118** [comment]
Please use the appropriate template for submitting this type of issue. You want to use "bug report" and fill the information as best as you can.

**Comment by Renber78** [comment]
Indeed, I also see this behavior.

- Change with NVS Editor -> value not saved after reboot
- Change with LMS Server (squeezeESP32 plugin) -> value saved after reboot

Tested with new version 1539

**Comment by philippe44** [comment]
It's not exactly that. It's that if you change it "manually" in NVS, then LMS will overwrite it. The value from NVS is not sent to LMS at boot. If you don't have LMS, then it will stick. So either you use a LMS server and you must set it up from there or you don't and then you use NVS. Using NVS is moot when LMS' job is to do these settings. That's the same for equalizer.

**Comment by sle118** [comment]
Consider the NVS/Audio settings from the GUI as a way to do a temp override when not close to a LMS
