### ISSUE TITLE
BT Speaker playback problems with radio streams

### ISSUE THREAD

**Issue by roresrores** [sle118/squeezelite-esp32#310]
Hello, I listen often those radio streams. 128kb/s at home and 48kb/s on holidays:

[http://stream.srg-ssr.ch/drs3/mp3_128.m3u](url)
Codec: MPEG Audio layer ½ (mpga)
Sample rate: 48kHz
Bits per sample: 32
Bitrate: 128kb/s

[http://stream.srg-ssr.ch/m/drs3/aacp_96.m3u](url)
[http://stream.srg-ssr.ch/m/drs3/aacp_32.m3u](url)
Codec: MPEG AAC Audio (mp4a)
Sample rate: 48kHz
Bits per sample: 32
Bitrate: 96kb/s (48kb/s)
AAC extension: SBR

I have:
LMS 8.3.1 (Debian Docker) 
Lolin D32 pro with I2S-4MFlash 2.1539-16 and Plugin SqueezeESP32 (v0.501) as a player.

It's a clear installation with nothing else configured.

With I2S Dac playback, everything works fine!

When I select “Bluetooth” as Output, the mp3_128.m3u Stream is playing to slowly (speed)!

And both Streams aacp_96.m3u and aacp_32.m3u wont play any more!

LMS Logfile:
[23-09-23 07:04:48.4196] Slim::Player::Song::open (424) Error: Couldn't create command line for aac playback for [http://stream.srg-ssr.ch/m/drs3/aacp_96]
[23-09-23 07:06:28.5903] Slim::Player::Song::open (424) Error: Couldn't create command line for aac playback for [http://stream.srg-ssr.ch/m/drs3/aacp_32]

Telnet ESP32 when I start playing aacp_96.m3u or aacp_32.m3u:
squeezelite-esp32> [00:39:37.632] decode_flush:251 decode flush
[00:39:37.633] output_flush:446 flush output buffer
[00:39:37.634] decode_flush:251 decode flush
[00:39:37.635] output_flush:446 flush output buffer
I (488389) bt_app_source: Output state is OUTPUT_STOPPED. Stopping a2dp media ...
I (488459) bt_app_source: a2dp media stopped successfully...
I (495749) bt_app_source: event: 13

**Comment by sle118** [comment]
https://github.com/sle118/squeezelite-esp32#raw-wrover-module
