### ISSUE TITLE
led_vu issue

### ISSUE THREAD

**Issue by philippe44** [sle118/squeezelite-esp32#318]
@wizmo2 : I don't know if you saw that https://forums.slimdevices.com/forum/user-forums/3rd-party-hardware/108002-announce-the-squeezeamp-next-generation-squeezeboxen-amplifier-receiver?p=1650966#post1650966

**Comment by wizmo2** [comment]
Can we push a new release?  This is the #303 issue

**Comment by philippe44** [comment]
Done
