### ISSUE TITLE
cli or api?

### ISSUE THREAD

**Issue by dionisor** [sle118/squeezelite-esp32#32]
Any command line or api to change "SQUEEZELITE COMMAND"?
I'd like to change bt connection from Home Automation System.

Thanks!!!

**Comment by philippe44** [comment]
no plan for the moment

**Comment by sle118** [comment]
It is true that there is no direct method that currently supports this, and no plan for this specific requirement, but you might want to have a look at this
https://github.com/sle118/squeezelite-esp32/commit/293d08deec74113df02f2c9c27e0d67944085861

The Master CMake branch how exposes a subset of the console commands which you could possibly leverage from your home automation system. The autoexec line is a simple NVS value and you could issue a command via the new API to update it and reboot the system.

**Comment by dionisor** [comment]
> It is true that there is no direct method that currently supports this, and no plan for this specific requirement, but you might want to have a look at this
> [293d08d](https://github.com/sle118/squeezelite-esp32/commit/293d08deec74113df02f2c9c27e0d67944085861)
> 
> The Master CMake branch how exposes a subset of the console commands which you could possibly leverage from your home automation system. The autoexec line is a simple NVS value and you could issue a command via the new API to update it and reboot the system.

I'm thinking in a similar idea. You could define as many autoexec variables as you need (autoexec%i, like profiles). Then you need a "selector var" that execute only autoexecX... 
I thought that autoexec var would act as "selector", but not.
It can be a workarround.

I'm going to review CMake branch as you suggested. 
Thanks!!!!
