### ISSUE TITLE
v2.1616 missing elements from the web UI 

### ISSUE THREAD

**Issue by Renber78** [sle118/squeezelite-esp32#331]
Quick message to report that today's version 'v2.1616-16' is bugged in the web interface.
- Status information is missing
- Hardware options are missing (SPI/Display/...)

Return to 'v2.1607-16' -> ok

**Comment by sle118** [comment]
Some hardware options have drifted from their original implementation, as features were added. This means GPIO in the status tab would be missing entries and that some hardware options would no longer generate the correct NVS format. I am thinking about a possible way to resolve this, but until then hardware options will have to be set via the NVS editor following the readme intructions. 

The other factor is space constraints. We are running out of room on the flash memory, and adding new features sometimes mean we have to spend more time on squeezing space to fit the feature than on the faire itself.

**Comment by Renber78** [comment]
ok, if it's voluntary that suits me.
I was already configuring via NVS.
My message was in case you hadn't seen it (bug)

**Comment by sle118** [comment]
I appreciate the input, sometimes the workflow build isn't perfectly aligned with the local build, so having feedback is always appreciated!
