### ISSUE TITLE
[UI] missing hardware features

### ISSUE THREAD

**Issue by 7-7-7** [sle118/squeezelite-esp32#337]
I want to start with thank you.  Awesome product.  I don't want to complain but i have discovered the following issue.

The hardware tab on version 
[2.1619-16#v4.3#I2S-4MFlash#master-v4.3](https://github.com/sle118/squeezelite-esp32/releases/tag/I2S-4MFlash.16.1619.master-v4.3)
is not the same as the hardware tab on version
[2.1598-16#v4.3#I2S-4MFlash#master-v4.3](https://github.com/sle118/squeezelite-esp32/releases/tag/I2S-4MFlash.16.1619.master-v4.3)

Version 1619 only have 
- Preset Options
- Led Strip Options
- I2C Bus Parameters
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/91600255-144a-480d-909f-7a056c221cc5)

Version 1598 have
- Preset Options
- DAC Options
- SPDIF Options
- Rotary Control
- Led Strip Options
- I2C Bus Parameters
- SPI Bus Parameters
- Display
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/9828de05-6062-4f76-833f-5a1cb96158d2)
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/27199a23-d54e-4d78-8691-1104c34911d4)
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/f99ed212-681f-463c-9a37-d9a2210ac5e0)
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/24c42d97-81bc-4d3a-8063-f098c690272e)
![image](https://github.com/sle118/squeezelite-esp32/assets/4107612/c3424dc6-d618-4c93-840e-2285ddc03f33)

I did a fresh install of version 1619 from this sight and selected erase every thing
https://sle118.github.io/squeezelite-esp32-installer/
and then I noticed the settings is missing.  I then downgraded to 1598 and the settings is back.
I then upgraded back to 1619 and the settings is missing again.

**Comment by sle118** [comment]
Thank you for taking the time to report this. In the upcoming versions, I have decided to fold back on the UI, trimming some features, in order to free up some space on the flash since it is getting more and more difficult to fit new features. In addition to this, the UI was getting misaligned with some newer features and thus the recommendation right now is to follow the readme to configure the hardware using the NVS editor.
