### ISSUE TITLE
Headphones output (i2s-m4flash) not working in latest version

### ISSUE THREAD

**Issue by cucko** [sle118/squeezelite-esp32#354]
As title says: Headphones output stopped working in latest release - I2S-4MFlash-1643 (and some releases before).
tried to downgrade to 2.1621-16, again, output not working.
downgraded to fw: I2S-4MFlash.16.2.1230 (i had the binary in my downloads) and it's all good. 

I don't use that player so often, so i don't know with which update the headphones output stopped working.

### Hardware Details
- ESP32 audio dev kit

**Comment by sle118** [comment]
https://github.com/sle118/squeezelite-esp32/blob/master-v4.3/.github/ISSUE_TEMPLATE/bug_report.md

Logs are invaluable here unless @philippe44 knows exactly what could be causing this

**Comment by philippe44** [comment]
No I don't - I checked on SqueezeAMP and jack detection is still working properly

**Comment by cucko** [comment]
i updated again to latest firmware, and all works fine. closing the ticket. thanks for the fast responses.
