### ISSUE TITLE
spotify repeat function via cspot is not working

### ISSUE THREAD

**Issue by urknall** [sle118/squeezelite-esp32#363]
### Describe the bug:
When i play a track or playlist via cspot on the squeezeamp, you cannot activate the repeat function on the smartphone in the spotify app.

### Preliminary Information

1. **Firmware Version**: v1.0-1652-16
2. **Plugin Version**: not using lms, directly from spotify app to cspot

### Hardware Details

Please describe your hardware setup: Latest squeezeamp batch

**Comment by sle118** [comment]
Please follow the bug posting guidelines
https://github.com/sle118/squeezelite-esp32/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by urknall** [comment]
> Please follow the bug posting guidelines https://github.com/sle118/squeezelite-esp32/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Updated...

**Comment by philippe44** [comment]
CSpot does not support that AFAIK

**Comment by urknall** [comment]
Ok, thank you. I will open a feature request.
