### ISSUE TITLE
Feature Request: WPA3/802.1x support

### ISSUE THREAD

**Issue by OscillateWildly** [sle118/squeezelite-esp32#374]
I'd like to ask that WPA3 and 802.1x support be put on the roadmap.  I recognize that this may not be a priority, or feasible in the foreseeable future, but it'd be a very nice enhancement.

**Comment by sle118** [comment]
Perhaps in the upcoming refactored version, depending on resources impact and support from the esp-idf v4.4.6

**Comment by sle118** [comment]
Closing this. No resource for this right now and heavy dependency on the esp-idf
