### ISSUE TITLE
Device Name Change does not Change Bluetooth Output Name

### ISSUE THREAD

**Issue by haldi4803** [sle118/squeezelite-esp32#378]
### Describe the bug
When you use the "New Name" button in System Tab it does NOT change the Bluetooth Name. Only LMS and Spotify Name

### Preliminary Information

1. **Firmware Version**: fw: I2S-4MFlash-1660

### Hardware Details
Irrelevant?

### NVS Settings
Interesting point here is that the "a2dp_dev_name" DOES correctly change, but the "a2dp_sink_name" which is also shown in the "Audio" Tab at "Bluetooth Audio Output Options" "Bluetooth audio device name. This applies when output mode is Bluetooth"

### Issue Description

1. **Observed Behavior**: The Bluetooth Output name stays the same.
2. **Expected Behavior**: Should also change
3. **Steps to Reproduce**: Change the name

**Comment by sle118** [comment]
a2dp_sink_name refers to a device you are attempting to connect to when output is set to Bluetooth. So changing a device's name shouldn't affect this. Do not confuse this with a2dp_dev_name, which is the name the device broadcasts to media devices like phones, etc.
