### ISSUE TITLE
Feature request: Possibility to configure lms cli port

### ISSUE THREAD

**Issue by fvzeppelin** [sle118/squeezelite-esp32#394]
The current software seems to have port 9090 hardcoded for the lms cli port. The possibility to configure this port would be great in order to easily set the software up for an lms with a different port setting.

**Comment by sle118** [comment]
Have you tried with a LMS configured with a different port? If so, please share logs. If not, please try.

https://github.com/sle118/squeezelite-esp32/blob/7b9deb795cf868dd1efa15e7e1109cd40b12a288/components/squeezelite/slimproto.c#L851

Seems to me that the discovery process should take care of setting ports automatically, but this isn't my area of expertise. @philippe44 ?

**Comment by fvzeppelin** [comment]
yes, I agree that it should be discovered. I was requesting this because my ssd1306 displays only the ip and the port of the server, nothing else, no metadata when playing. But seems like I was on the wrong track here.

**Comment by fvzeppelin** [comment]
Ah, now that I activated the esp32 plugin on server-side, everything is perfectly fine :)
