### ISSUE TITLE
GPIO for amp not working

### ISSUE THREAD

**Issue by matty67** [sle118/squeezelite-esp32#396]
I updated from 2.1662-16 to [1670 ](fw: I2S-4MFlash-1670, mode: Squeezelite-ESP32)

With this version my setting for set_GPIO 27=amp is not working.
I also tried some different GPIO´s but that´s not working too.
When I go back to 1662 everything works perfect.

**Comment by sle118** [comment]
Please follow the process to open issues providing complete information.
