### ISSUE TITLE
Wifi wont connect ever

### ISSUE THREAD

**Issue by kevindebosscher** [sle118/squeezelite-esp32#409]
![muse](https://github.com/sle118/squeezelite-esp32/assets/23461848/2ccb61c3-0a4b-4446-92ce-c5e82fef0dcc)

See picture, running latest build installed via the web loader fw: Muse-1672
Issue is the same on 2 Luxe Muse speakers, flashing goes perfectly fine!
But none of them connect succefully on any available Wlan.
After 30min waiting still the above picture...

ESPhome firmware works and connects just fine

**Comment by sle118** [comment]
There's a template for issues. Please use it so I don't have to repeat the same questions for every new issue
https://github.com/sle118/squeezelite-esp32/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
