### ISSUE TITLE
Disable led in software?

### ISSUE THREAD

**Issue by DarkShortie** [sle118/squeezelite-esp32#41]
I've build a Squeezeamp and I'm using it in my sleeping room. When no playback is active the led is blinking which is relay annoying when you try to sleep.
Is it possible to disable the led completely with some software switch or nvs property?

**Comment by ElFishi** [comment]
I don't have a SqueezeAMP, but I presume in the NVS config under set_GPIO it says 
12=green:0

If so, change it to 
12=Vcc
This will tell the system to keep GPIO12, which is connected to the green LED, high so it stays off.

**Comment by DarkShortie** [comment]
set_GPIO was empty, I've changed it to 12=Vcc and rebooted, but nothing changed

**Comment by ElFishi** [comment]
the other LED should be 13, but maybe someone who knows better should chime in...

**Comment by philippe44** [comment]
It's fixed for SqueezeAMP, the set_GPIO only works if you use the I2S version. Having said that, you can use this version and set manually all SqueezeAMP I/O's except for the LEDs. I've verified that in the past when I moved all parameters to be usable from NVS

**Comment by philippe44** [comment]
I've now added PWM control on the green and red LEDs. Use the NVS parameter 'led_brightness' and set a value between 0 and 100
