### ISSUE TITLE
Is it possible to add DLNA support ?

### ISSUE THREAD

**Issue by bepluy** [sle118/squeezelite-esp32#413]
It's very great project for LMS and Airplay. But is it any chance to have DLNA support for streaming natively from Android phones or PC without 3rd party app like AirMusic/TuneBlade/etc ?
Since many Android music players or Chrome have native support to stream over DLNA - it would be great.

**Comment by sle118** [comment]
This project focuses on implementing a multi-room playback device and services implemented outside of this were just "gravy". There are good LMS plugins for streaming to squeezelite via DLNA, so no, this isn't happening with this project.

thank you!
