### ISSUE TITLE
[Feature Request] more than SBC when BT is source

### ISSUE THREAD

**Issue by legolas136** [sle118/squeezelite-esp32#415]
Is it possible to get other codecs as BT input working?

When playing flacs over lms the sound is really nice with the pcm5102 over I²S. But when using BT as source, the sound is muffled... As always with SBC codec.
APT-X HD or even LDAC would be awesome.

**Comment by sle118** [comment]
We are leveraging the esp-idf Bluetooth stack and thus are limited by their offerings. If someone finds an alternative that can be used in this project, I'd be willing to take a look, but otherwise I'm afraid this won't be possible in the near future. 

Thank you
