### ISSUE TITLE
Setting bt_sink_pin doesnt reflect in pairing a new device 

### ISSUE THREAD

**Issue by the-mentor** [sle118/squeezelite-esp32#423]
### Describe the bug
When I set bt_sink_pin to a specific pin and then i try to pair from my phone to the ESP32 running Squeezelite i don't have to enter the pin to pair.

### Preliminary Information

1. **Firmware Version**: Specify the version of the firmware you are using.

### Hardware Details

Please describe your hardware setup:

- **ESP32 Module**: ESP32A1S
- **Board Type**: ESP32 Audio Kit v2.2
- **DAC Chip**: ES8388
- **Additional Hardware**: None

Thanks in advance.
-DM

**Comment by sle118** [comment]
This is known and for now there's no short term fix in view.
