### ISSUE TITLE
Flash instructions

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [sle118/squeezelite-esp32#429]
There's no info whatsoever how to flash this thing. I assume building is optional since you provide binary so how do I flash it there's literally 0 info on that

**Comment by iceman73** [comment]
https://sle118.github.io/squeezelite-esp32-installer/

**Comment by Michal-Szczepaniak** [comment]
It doesn't work in every browser, and requiring browser to flash is bit meh

**Comment by iceman73** [comment]
https://github.com/sle118/squeezelite-esp32/discussions/129

**Comment by Michal-Szczepaniak** [comment]
So please add both to Readme under Installation secition and it will be golden

**Comment by sle118** [comment]
> So please add both to Readme under Installation secition and it will be golden

You can also submit a pull request with your suggestions and I'll gladly review them. 

Thanks @iceman73
