### ISSUE TITLE
rtl8720dn

### ISSUE THREAD

**Issue by giabaodragon** [sle118/squeezelite-esp32#431]
How use for rtl8720dn?

**Comment by sle118** [comment]
Please elaborate

**Comment by sle118** [comment]
@giabaodragon noir sur if you read the name of the project, but if not I would encourage you to do so. 

Assuming this is feasible from a hardware standpoint, it would need its own port from the ground up. 

Esp32-wrover modules are cheap and available from numerous sources, so no. This ain't happening. 

Thank you
