### ISSUE TITLE
ESP32-Wrover-DEV install fails

### ISSUE THREAD

**Issue by mingratta** [sle118/squeezelite-esp32#433]
![Picture of board](https://github.com/user-attachments/assets/400399f7-f892-4af2-b81c-e7ab0c279ab4)

[esp-web-tools-logs (14).txt](https://github.com/user-attachments/files/16521740/esp-web-tools-logs.14.txt)

### Describe the bug
When flashing the ESP32-Wrover-DEV device with Squeezelite the flash looks successful however the flash fails. 

### Hardware Details

- ESP32 Module: ESP32-WROVER-Dev
- 4MB Flash memory, and 8MB PSRAM
- Microcontroller: ESP32-WROVER-E
- Processor: Dual-core 32-bit MCU with 600 DMIPS
- Bluetooth: Bluetooth v4.2 BR/EDR and BLE

Logs Attached

### Issue Description
1. I plugged the device into the computer
2. Selected Generic/I2s  the install page. 
3. Held the boot button down and connected to serial and clicked install.
4. selected ease device and installed, no errors on install. 
5. when restarting the device its in a boot loop attached is the log.

**Comment by Renber78** [comment]
Hello, do you have GPIO connected? if yes which ones?

**Comment by criegit** [comment]
I actually have the same problem. I tried installers
https://sonocotta.github.io/esp32-audio-dock/
and
https://sle118.github.io/squeezelite-esp32-installer/

The first brought me usually the error very similar to the one from mingratta.
The second installer gives me a slightly different error message and also (i think) keeps resetting. (see below)
I tried two different boards of the same make. Nothing connected., no camera attached. 
Flashing and running esphome seems to work fine.

WROVER Module (same as in original post) error message: (same if i hold boot during pluggin in and then pres "Reset Device" or just plug it in directly.)
```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6424
load:0x40078000,len:15632
load:0x40080400,len:4348
entry 0x40080688
I (27) boot: ESP-IDF v4.3.5-dirty 2nd stage bootloader
I (27) boot: compile time 21:43:45
I (27) boot: chip revision: v1.0
I (31) qio_mode: Enabling default flash chip QIO
I (36) boot.esp32: SPI Speed      : 80MHz
I (40) boot.esp32: SPI Mode       : QIO
I (45) boot.esp32: SPI Flash Size : 4MB
I (50) boot: Enabling RNG early entropy source...
I (55) boot: Partition Table:
I (59) boot: ## Label            Usage          Type ST Offset   Length
I (66) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (73) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (81) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (88) boot:  3 recovery         factory app      00 00 00010000 00140000
I (96) boot:  4 ota_0            OTA app          00 10 00150000 002a0000
I (103) boot:  5 settings         WiFi data        01 02 003f0000 00010000
I (111) boot: End of partition table
I (115) boot: Defaulting to factory image
I (120) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=53878h (342136) map
I (223) esp_image: segment 1: paddr=000638a0 vaddr=3ffbdb60 size=04858h ( 18520) load
I (228) esp_image: segment 2: paddr=00068100 vaddr=40080000 size=07f18h ( 32536) load
I (239) esp_image: segment 3: paddr=00070020 vaddr=400d0020 size=d1744h (857924) map
I (476) esp_image: segment 4: paddr=0014176c vaddr=40087f18 size=0c8b8h ( 51384) load
I (493) esp_image: segment 5: paddr=0014e02c vaddr=400c0000 size=00068h (   104) load
I (503) boot: Loaded app from partition at offset 0x10000
I (503) boot: Disabling RNG early entropy source...
I (515) psram: This chip is ESP32-D0WD
ets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

.... (continues with last message indefinitely)
```

If i press "Reset Device" i get a different restart reason once (makes sense)
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
```

Unrelated:
Using https://sonocotta.github.io/esp32-audio-dock/ and another esp32-s3 xiao board i managed to get it installed and booted once, but it then does not boot a second time. And since i also want the BT streaming option, i decided to go to the brand new esp32 wrover modules anyway and abandonned the (faster) esp32-s3.

**Comment by criegit** [comment]
can anybody confirm that the offset and length of the flashed firmware is correct?
https://esp32.com/viewtopic.php?t=19176

I just tried a third installer without luck, but a new error message.
https://raspiaudio.github.io/

```
rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6480
load:0x40078000,len:15868
load:0x40080400,len:4384
csum err:0xc6!=0x56
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6480
load:0x40078000,len:15868
load:0x40080400,len:4384
csum err:0x98!=0x56
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6480
load:0x40078000,len:15868
load:0x40080400,len:4384
entry 0x40080684
I (27) boot: ESP-IDF v4.3.2-dirty 2nd stage bootloader
I (27) boot: compile time 21:33:16
I (27) boot: chip revision: 1
I (31) qio_mode: Enabling default flash chip QIO
I (36) boot.esp32: SPI Speed      : 80MHz
I (41) boot.esp32: SPI Mode       : QIO
I (45) boot.esp32: SPI Flash Size : 4MB
I (50) boot: Enabling RNG early entropy source...
E (55) flash_parts: partition 0 invalid magic number 0xdcee
E (61) boot: Failed to verify partition table
E (66) boot: load partition table error!
ets Jun  8 2016 00:22:57

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6480
load:0x40078000,len:15868
load:0x40080400,len:4384
csum err:0x0c!=0x56
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6480
load:0x40078000,len:15868
load:0x40080400,len:4384
csum err:0x10!=0x56
ets_main.c 371 
ets Jun  8 2016 00:22:57
```

**Comment by Renber78** [comment]
ESP32-D0WD = no psram !

**Comment by criegit** [comment]
ok. Thank you a lot!
 And based on the instructions i thought all WROVER work...

Any tips which one works? How can i identify it? Most shops Amazon/ebay only list the name but no detailed description.
And i do not need the full audio boards. i just want a simple SPDIF digital out to my stereo...

**Comment by Renber78** [comment]
I use ESP32-WROVER-B or ESP32-WROVER-E which works very well. 
Namely: WROVER-IE = external antenna  /  WROVER-E = internal antenna (same for B)

**Comment by criegit** [comment]
That sounds good, but both of our modules say WROVER-E... (etched on the lid)

I know that these ESP names are confusing, but until today i thought i am able to get through it. 
Did we both just get a faked module?

**Comment by Renber78** [comment]
You probably have fake ones then, yes.
To my knowledge the E & B all have PSRAM. The ID you have in your logs reminds me of an old ESP-VROOM-32.
I don't have the ID of "mingratta", so it's impossible to know if he is in the same situation as you.

**Comment by Renber78** [comment]
Do you have a link or a diagram of your card?

**Comment by criegit** [comment]
I just tried this script from [https://thingpulse.com/esp32-how-to-use-psram/](https://thingpulse.com/esp32-how-to-use-psram/) and  finally got it running with my home pc. (really bad Antivirus at work)
Result:
[  5033][D][main.cpp:5] setup(): Total heap: 380488
[  5039][D][main.cpp:6] setup(): Free heap: 357052
[  5045][D][main.cpp:7] setup(): Total PSRAM: 0
[  5052][D][main.cpp:8] setup(): Free PSRAM: 0

It is this amazon link:
https://www.amazon.de/dp/B0B96DKMQK

**Comment by Renber78** [comment]
After reading some espressif docs, I believe it is possible to have this ID with PSRAM (but external). So this may not be the path to follow...

**Comment by criegit** [comment]
I think the D0WD is just the chip. If it was D0WDR2, it would have internal on-chip psram. The D0WD needs it additionally on the PCB externally. (e.g. https://www.digikey.de/de/products/detail/espressif-systems/ESP32-WROVER-E-N16R8/11613135)

BUT every WROVER-E should have PSRAM, i think:
Page 1(after index):
https://www.espressif.com/sites/default/files/documentation/esp32-wrover-e_esp32-wrover-ie_datasheet_en.pdf

**Comment by Renber78** [comment]
yes that's what I understood too

**Comment by Renber78** [comment]
otherwise, you can flash your ESP32 with the camera example under Arduino. It will use PSRAM and you should see this in the logs. If you have the same type of error it is because the seller 'forgot' to solder it ;-)
At the same time seeing the description of the product on Amazon... the seller is not very serious.
Also check that GPIO 12 is high at startup, you can also try in low state

**Comment by criegit** [comment]
camera sketch via arduino has similar results. not booting up.
PIN12 will be tried in the next days.

**Comment by criegit** [comment]
I got new boards from Soldered (https://soldered.com/de/produkt/dasduino-connectplus/)

They are looking really well made, price is ok and squeezelite worked immediately.

**Comment by nehasjains** [comment]
> I got new boards from Soldered (https://soldered.com/de/produkt/dasduino-connectplus/)
> 
> They are looking really well made, price is ok and squeezelite worked immediately.

Can you plz give the details of the board, the link you shared says "page not found".

**Comment by criegit** [comment]
called
Dasduino connectplus
seems to be no longer in production/sale. sorry

**Comment by nehasjains** [comment]
> called Dasduino connectplus seems to be no longer in production/sale. sorry

Ok. Could you plz recommend any board that would be compatible

**Comment by criegit** [comment]
sorry. no idea.
