### ISSUE TITLE
Airplay volume bug ?

### ISSUE THREAD

**Issue by PVerburg** [sle118/squeezelite-esp32#44]
Running bleeding.edge.72-ESP32-A1S 
If issuing remotely volume 1 ie max in airplay mode no audio output but 0.98?????? or lower is fine.

I have been looking for other problems and found this was a cause of my struggles  the same problem in earlier versions ie 62 and 66 I think I have played with.

Not a big problem now i know.

Thanks Paul V.

**Comment by philippe44** [comment]
Thanks - I thought I fixes that but I obviously did not. I've pushed the modification now
