### ISSUE TITLE
[Question]All my different ESP32 do not open the SSID squeezlite after flashing.

### ISSUE THREAD

**Issue by Haifeif** [sle118/squeezelite-esp32#447]
I tried 4 different ESP32 dev boards, and I used 2 different browser: still after finishing the firmware flash, there is no SSID squeezlite available.

1. I2S-4MFlash-16 2.1681
2. I dont get that far 😁

**Comment by sle118** [comment]
There's nothing much I can do without at least some logs. If you flashed some boards using the serial port, then you can get them and see what is going on. 

There's a lot of bad esp32 boards out there, and the majority don't have psram. So come back with some logs and maybe we can advise.
