### ISSUE TITLE
-s disable option seems not working

### ISSUE THREAD

**Issue by ferrarid61** [sle118/squeezelite-esp32#453]
### Describe the bug
I'm using a sueezelite-esp32 on esp32  wrover E CPU. I installed it with the web installer. I want to avoid the LMS connection bat the --s disable option in autoexec1 seems not have any effect ad the cpu reboots prediodically

### Preliminary Information

1. **Firmware Version**:  fw: I2S-4MFlash-1681, mode: Squeezelite-ESP32
2. **Plugin Version**: Mention the version of the plugin installed on your LMS (Logitech Media Server).

### Hardware Details

Please describe your hardware setup:

- **ESP32 Module**: ESP32 WROVER E.
- **Board Type**: If applicable, e.g., ESP32 audio kit, etc.
- **DAC Chip**: PMC5201A.
- **Additional Hardware**: Include details about any other hardware like rotary controls, buttons, screens (SPI, I2C), Ethernet, IO expansion, etc.

### NVS Settings

Follow these steps to share your NVS settings:

1. Open the web UI of your device.
2. Click on the "Credit" tab.
3. Enable the "Show NVS Editor" checkbox. This allows you to view or change the NVS configuration even when not in recovery mode.
4. Navigate to the "NVS Editor" tab.
5. Scroll to the bottom and click "Download Config".
6. Share the downloaded content here.

<details>
<pre><code>
{
  "a2dp_ctmt": "1000",
  "a2dp_ctrld": "500",
  "a2dp_dev_name": "cambridge",
  "a2dp_sink_name": "cambridge",
  "a2dp_spin": "0000",
  "actrls_config": "",
  "airplay_name": "cambridge",
  "airplay_port": "5000",
  "ap_channel": "1",
  "ap_ip_address": "192.168.4.1",
  "ap_ip_gateway": "192.168.4.1",
  "ap_ip_netmask": "255.255.255.0",
  "ap_pwd": "squeezelite",
  "ap_ssid": "cambridge",
  "autoexec": "1",
  "autoexec1": "squeezelite  -o i2s  -s  disable -b  500:2000 -C  30 -d  all=info ",
  "bat_config": "",
  "bt_name": "cambridge",
  "bt_sink_pin": "1234",
  "bt_sink_volume": "127",
  "bypass_wm": "0",
  "cspot_config": "{\"deviceName\":\"cambridge\",\"bitrate\":160,\"zeroConf\":1}",
  "dac_config": "model=,bck=33,ws=25,do=32",
  "dac_controlset": "",
  "dhcp_tmout": "8",
  "display_config": "",
  "enable_airplay": "1",
  "enable_bt_sink": "1",
  "enable_cspot": "1",
  "equalizer": "",
  "eth_config": "",
  "ethtmout": "8",
  "gpio_exp_config": "",
  "host_name": "cambridge",
  "i2c_config": "",
  "jack_mutes_amp": "n",
  "led_brightness": "",
  "led_vu_config": "",
  "lms_ctrls_raw": "n",
  "loudness": "0",
  "metadata_config": "",
  "model_config": "",
  "ota_erase_blk": "249856",
  "ota_prio": "6",
  "ota_stack": "10240",
  "pollmin": "15",
  "pollmx": "600",
  "rel_api": "https://api.github.com/repos/sle118/squeezelite-esp32/releases",
  "release_url": "CONFIG_SQUEEZELITE_ESP32_RELEASE_URL",
  "rotary_config": "",
  "set_GPIO": "",
  "sleep_config": "",
  "spdif_config": "",
  "spi_config": "",
  "stats": "n",
  "target": "",
  "telnet_block": "500",
  "telnet_buffer": "40000",
  "telnet_enable": ""
}</code></pre>
</details>

### Logs

To share logs:

1. Connect your player to a computer using a USB cable. Use a built-in Serial-USB adapter if your player has one, or an external USB adapter otherwise.
2. Go to the [web installer](https://sle118.github.io/squeezelite-esp32-installer/).
3. Click "Connect to Device".
4. Select the appropriate serial port.
5. Click "Logs And Console".
6. Download the logs and share them here. Please remove any sensitive information like Wi-Fi passwords or MAC addresses.
- **If the problem occurs soon after booting**: Share the full log until the issue occurs.
- **If the problem occurs later during playback**: Trim the logs to include information just before and after the problem occurs.

#### Example Log

Here's an example log for reference. Make sure to obfuscate sensitive information like Wi-Fi passwords, MAC addresses, and change IP addresses to something more generic.

<details>
<pre><code>
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6424
load:0x40078000,len:15632
load:0x40080400,len:4348
entry 0x40080688
I (27) boot: ESP-IDF v4.3.5-dirty 2nd stage bootloader
I (27) boot: compile time 09:34:07
I (27) boot: chip revision: v3.1
I (31) qio_mode: Enabling default flash chip QIO
I (36) boot.esp32: SPI Speed      : 80MHz
I (41) boot.esp32: SPI Mode       : QIO
I (45) boot.esp32: SPI Flash Size : 4MB
I (50) boot: Enabling RNG early entropy source...
I (55) boot: Partition Table:
I (59) boot: ## Label            Usage          Type ST Offset   Length
I (66) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (74) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (81) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  3 recovery         factory app      00 00 00010000 00140000
I (96) boot:  4 ota_0            OTA app          00 10 00150000 002a0000
I (104) boot:  5 settings         WiFi data        01 02 003f0000 00010000
I (111) boot: End of partition table
I (115) esp_image: segment 0: paddr=00150020 vaddr=3f400020 size=aeb20h (715552) map
I (321) esp_image: segment 1: paddr=001feb48 vaddr=3ffbdb60 size=014d0h (  5328) load
I (323) esp_image: segment 2: paddr=00200020 vaddr=400d0020 size=1b3048h (1781832) map
I (818) esp_image: segment 3: paddr=003b3070 vaddr=3ffbf030 size=0456ch ( 17772) load
I (823) esp_image: segment 4: paddr=003b75e4 vaddr=40080000 size=1e01ch (122908) load
I (863) esp_image: segment 5: paddr=003d5608 vaddr=400c0000 size=00068h (   104) load
I (879) boot: Loaded app from partition at offset 0x150000
I (879) boot: Disabling RNG early entropy source...
I (890) psram: This chip is ESP32-D0WD
I (890) spiram: Found 64MBit SPI RAM device
I (891) spiram: SPI RAM mode: flash 80m sram 80m
I (894) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (901) cpu_start: Pro cpu up.
I (905) cpu_start: Starting app cpu, entry point is 0x40081400
I (0) cpu_start: App cpu up.
I (1410) spiram: SPI SRAM memory test OK
I (1423) cpu_start: Pro cpu start user code
I (1423) cpu_start: cpu freq: 240000000
I (1423) cpu_start: Application information:
I (1426) cpu_start: Project name:     Squeezelite-ESP32
I (1432) cpu_start: App version:      I2S-4MFlash-1681
I (1437) cpu_start: Compile time:     Sep 12 2024 09:35:40
I (1444) cpu_start: ELF file SHA256:  0000000000000000...
I (1450) cpu_start: ESP-IDF:          v4.3.5-dirty
I (1455) cpu_start: Min chip rev:     v1.0
I (1460) cpu_start: Max chip rev:     v3.99 
I (1465) cpu_start: Chip rev:         v3.1
I (1470) heap_init: Initializing. RAM available for dynamic allocation:
I (1477) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (1483) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (1489) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1496) heap_init: At 3FFC6EC8 len 00019138 (100 KiB): DRAM
I (1502) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1508) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1515) heap_init: At 4009E01C len 00001FE4 (7 KiB): IRAM
I (1521) spiram: Adding pool of 4018K of external SPI memory to heap allocator
I (1530) spi_flash: detected chip: generic
I (1534) spi_flash: flash io: qio
I (1541) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1549) spiram: Reserving pool of 64K of internal memory for DMA/internal allocations
I (1559) esp_app_main: System is booting from power on.
I (1569) esp_app_main: Reset reason is: 1
I (1569) esp_app_main: Reboot counter=1

I (1569) esp_app_main: Starting app_main
I (1579) nvs_utilities: Initializing flash nvs 
I (1599) nvs_utilities: Initializing nvs partition settings
I (1639) esp_app_main: Setting up telnet.
I (1639) telnet: Telnet support disabled
I (1639) esp_app_main: Setting up config subsystem.
W (1719) nvs_utilities: Configuration memory usage.  Heap internal:229063 (min:228919) (used:216) external:4095207 (min:4087599) (used:15440)
I (1719) esp_app_main: Registering default values
I (1729) system_api: Base MAC address is not set
I (1729) system_api: read default base MAC address from EFUSE
W (1739) config: Waiting for config commit ...
I (2719) config: configuration has some uncommitted entries
I (2719) config: Committing configuration to nvs. Locking config object.
I (2719) config: Done Committing configuration to nvs.
I (2719) config: Config committed!
I (2729) esp_app_main: Configuring services
I (2729) services: Configuring I2C sda:-1 scl:-1 port:1 speed:400000
W (2739) services: no I2C configured
I (2739) services: Configuring SPI mosi:-1 miso:-1 clk:-1 host:1 dc:-1
W (2749) services: no SPI configured
W (2759) led: LED GPIO -1 ignored
W (2759) led: LED GPIO -1 ignored
I (2759) led: Configuring LEDs green:-1 (on:0 rmt:-1 -1% ), red:-1 (on:0 rmt:-1 -1% )
I (2769) battery: No battery
I (2779) monitor: Initializing monitoring
I (2779) monitor: Heap internal:229739 (min:228847) external:4078631 (min:4078615) dma:221955 (min:221079)
I (2789) esp_app_main: Initializing display
I (2799) display: Trying to configure display with N/A
W (2799) display: No display driver
I (2809) esp_app_main: Initializing led_vu
I (2809) led_vu: led_vu configuration invalid
I (2809) esp_app_main: Checking for update url
W (2819) config: Value not found for key fwurl
W (2829) config: Value not found for key 
0;33mW (2839) config: Value not found for key apdelay
I (2839) uart: queue free spaces: 3
I (2839) network_handlers: Network manager configuration: polling max 10176, polling min 15000, ap delay 20000, dhcp timeout 8000, eth timeout 8000
I (2869) http_server: Initializing HTTP Server
I (2869) network_ethernet: Attempting to initialize Ethernet
I (2869) network_ethernet: No Ethernet configuration, or configuration invalid
I (2899) wifi:wifi driver task: 3ffdf9c8, prio:23, stack:6656, core=0
I (2899) wifi:wifi firmware version: 9ec65ef
I (2899) wifi:wifi certification version: v7.0
I (2899) wifi:config NVS flash: enabled
I (2909) wifi:config nano formating: disabled
I (2909) wifi:Init data frame dynamic rx buffer num: 40
I (2909) wifi:Init management frame dynamic rx buffer num: 40
I (2919) wifi:Init management short buffer num: 32
I (2919) wifi:Init static tx buffer num: 12
I (2929) wifi:Init tx cache buffer num: 32
I (2939) wifi:Init static rx buffer size: 1600
I (2939) wifi:Init static rx buffer num: 12
I (2949) wifi:Init dynamic rx buffer num: 40
I (2949) wifi_init: tcpip mbox: 32
I (2949) wifi_init: udp mbox: 32
I (2949) wifi_init: tcp mbox: 32
I (2959) wifi_init: tcp tx win: 8192
I (2959) wifi_init: tcp rx win: 32768
I (2969) wifi_init: tcp mss: 1440
I (2969) wifi_init: WiFi/LWIP prefer SPIRAM
I (2969) network_wifi: Starting wifi
I (2979) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (3069) wifi:mode : sta (a8:42:e3:ae:6e:ec)
I (3069) wifi:enable tsf
I (3069) network_handlers: Existing wifi config found. Attempting to connect.
I (3069) network: Starting DHCP client
I (3079) network_wifi: Wifi Connecting to XXXXXXX...

Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.

To automatically execute lines at startup:
	Set NVS variable autoexec (U8) = 1 to enable, 0 to disable automatic execution.
	Set NVS variable autoexec[1~9] (string)to a command that should be executed automatically

****************************
Your terminal application does not support escape sequences.
Line editing and history features are disabled.
On Windows, try using Putty instead.
****************************
W (3129) console: Processing autoexec commands while network manager active.  Wifi related commands will be ignored.
I (3139) console: autoexec is set to perform auto-process
I (3149) console: Running command autoexec1 = squeezelite  -o i2s  -s  disable -b  500:2000 -C  30 -d  all=info 
W (3169) config: Value not found for key autoexec2
squeezelite-esp32> I (3169) squeezelite_cmd: Calling squeezelite
[00:00:01.755] sb_controls_init:249 initializing audio (buttons/rotary/ir) controls (raw:0)
[00:00:01.756] sb_displayer_init:327 no display or led visualizer for LMS
[00:00:01.767] stream_init:539 init stream
[00:00:01.768] output_init_embedded:78 init device: i2s
[00:00:01.780] output_init_common:433 supported rates: 192000 176400 96000 88200 48000 44100 32000 24000 22050 16000 12000 11025 8000 
[00:00:01.792] output_init_embedded:100 init I2S/SPDIF
W (3219) DAC core: DAC does not use i2c
I (3219) DAC external: DAC on I2C @0
W (3229) DAC external: no i2c controlset found
[00:00:01.805] output_init_i2s:347 configuring MCLK on GPIO 0
I (3239) I2S: DMA Malloc info, datalen=blocksize=2048, dma_buf_count=12
I (3239) I2S: APLL: Req RATE: 44100, real rate: 44099.988, BITS: 16, CLKM: 1, BCK_M: 8, MCLK: 11289597.000, SCLK: 1411199.625000, diva: 1, divb: 0
[00:00:01.830] output_init_i2s:376 i2s DAC using I2S bck:33, ws:25, do:32, mute:-1:0 (res:0)
[00:00:01.842] output_init_i2s:396 Initializing I2S mode normal with rate: 44100, bits per sample: 16, buffer frames: 512, number of buffers: 12 
[00:00:01.854] equalizer_set_samplerate:122 equalizer sample rate 44100
[00:00:01. output_thread_i2s:518 Output state is -1
[00:00:01.865] output_visu_init:75 Initialize VISUEXPORT 512 16 bits samples
[00:00:01. output_init_embedded:108 init completed.
[00:00:01.867] output_thread_i2s:522 switching off amp GPIO -1
[00:00:01.878] decode_init:153 init decode
[00:00:01.889] register_alac:547 using alac to decode alc
[00:00:01.890] register_helixaac:686 using helix-aac to decode aac
[00:00:01.901] register_vorbis:526 using vorbis to decode ogg
[00:00:01.903] register_opus:458 using opus to decode ops
[00:00:01.903] register_flac:338 using flac to decode ogf,flc
[00:00:01.914] register_pcm:483 using pcm to decode aif,pcm
[00:00:01.915] register_mad:417 using mad to decode mp3
W (3349) BT_AV: BT Sink pin code is: [1234] 
I (3349) BTDM_INIT: BT controller compile version [2c56073]
[00:00:01.928] register_external:469 Initializing AirPlay sink
[00:00:01.939] register_external:480 Initializing CSpot sink
[00:00:01.944] discover_server:844 sending discovery 25
[00:00:01.955] discover_server:848 error sending discovery
I (3699) BT_AV: Bluetooth Init complete
I (4979) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (5569) wifi:state: init -> auth (b0)
I (5569) wifi:state: auth -> assoc (0)
I (5579) wifi:state: assoc -> run (10)
I (5619) wifi:connected with XXXXXXX, aid = 21, channel 1, BW20, bssid = 10:13:31:b8:80:b7
I (5619) wifi:security: WPA2-PSK, phy: bgn, rssi: -62
I (5629) wifi:pm start, type: 1

I (5639) network: Got an IP address from interface Wifi. IP=192.168.1.203, Gateway=192.168.1.254, NetMask=255.255.255.0, Address was changed
I (5649) esp_netif_handlers: sta ip: 192.168.1.203, mask: 255.255.255.0, gw: 192.168.1.254
I (5659) esp_app_main: Network connected and mDNS initialized with cambridge
[00:00:04.245] raop_sink_start:178 starting Airplay for ip 192.168.1.203 with servicename cambridge
[00:00:04.248] raop_create:201 starting mDNS with A842E3AE6EEC@cambridge
I (5689) cspot: starting Spotify on host cambridge
[00:00:04.294] I Shim.cpp:344: CSpot instance service name cambridge (id 142137fd329622137a1490160000000435587463)
[00:00:04.296] I Shim.cpp:331: ZeroConf mode (port 80)
I (5769) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[00:00:06.965] discover_server:844 sending discovery 24
I (10459) httpd_handlers: serving /messages.json to peer 192.168.1.181 port 45256
[00:00:11.971] discover_server:844 sending discovery 23
[00:00:16.986] discover_server:844 sending discovery 22
</code></pre>
</details>

### Issue Description

1. **Observed Behavior**: aqueezeite still try to contact LMS server and after e while reboots.
2. **Expected Behavior**: working with BT Airplay & Spotify.
3. **Steps to Reproduce**: Provide a step-by-step guide on how to replicate the issue.

**Comment by moesfeld** [comment]
It needs to be "-s -disable" not "-s disable". Notice the missing "-"

**Comment by ferrarid61** [comment]
> It needs to be "-s -disable" not "-s disable". Notice the missing "-"

Thank you so much!!
