### ISSUE TITLE
[Request]: Bluetooth: Add support for more codecs than SBC

### ISSUE THREAD

**Issue by duhow** [sle118/squeezelite-esp32#458]
Connecting to squeezelite-esp32 as `sink` (I2S-4MFlash-1672) , the following codecs are supported:

<img src="https://github.com/user-attachments/assets/6ef77e3c-b7d3-4c13-bbd0-da3e0e4151d3" height="500">

---

Requesting to add support for any of the following codecs:
- Opus
- [openaptX](https://github.com/arkq/openaptx) or [libreaptX](https://github.com/iamthehorker/libfreeaptx)
- [fdk-AAC](https://github.com/mstorsjo/fdk-aac)
- [LC3plus](https://github.com/arkq/LC3plus)

LDAC enconding requires a license.

**Comment by sle118** [comment]
@duhow our Bluetooth sink is built on top of the esp-idf a2dp stack which currently only support SBC. Unless someone if willing to invest the time in this, I'm afraid it will not happen. 

Thank you for the suggestion
