### ISSUE TITLE
ESP32-WROVER-IB LMS Player/ Bluetooth/ Airplay not working

### ISSUE THREAD

**Issue by Charliestonedassgueniapig** [sle118/squeezelite-esp32#459]
To help us resolve your issue as quickly as possible, please follow these guidelines when submitting an issue. Providing all the necessary information will save both your time and ours.

### Describe the bug
When installing squeezeeliteesp32 onto the device, it works you can configure ect but you cannot strream to it by any way.

### Preliminary Information

1. **Firmware Version**: I2S-4MFlash-1681
2. **Plugin Version**: /

### Hardware Details

Please describe your hardware setup:

- **ESP32 Module**: ESP32-WROVER-IB 
- **Board Type**: /
- **DAC Chip**: PCM5102
- **Additional Hardware**: /
### NVS Settings

Follow these steps to share your NVS settings:

1. Open the web UI of your device.
2. Click on the "Credit" tab.
3. Enable the "Show NVS Editor" checkbox. This allows you to view or change the NVS configuration even when not in recovery mode.
4. Navigate to the "NVS Editor" tab.
5. Scroll to the bottom and click "Download Config".
6. Share the downloaded content here.

<details>
<pre><code>
  {
  "a2dp_ctmt": "1000",
  "a2dp_ctrld": "500",
  "a2dp_dev_name": "Squeezelite",
  "a2dp_sink_name": "SMSL BT4.2",
  "a2dp_spin": "0000",
  "actrls_config": "",
  "airplay_name": "ESP32-AirPlay-aea06c",
  "airplay_port": "5000",
  "ap_channel": "1",
  "ap_ip_address": "192.168.4.1",
  "ap_ip_gateway": "192.168.4.1",
  "ap_ip_netmask": "255.255.255.0",
  "ap_pwd": "squeezelite",
  "ap_ssid": "squeezelite-aea06c",
  "autoexec": "1",
  "autoexec1": "squeezelite -o I2S -b 500:2000 -d all=info -C 30 -W -n squeezelite-aea06c",
  "bat_config": "",
  "bt_name": "ESP32-BT-aea06c",
  "bt_sink_pin": "1234",
  "bt_sink_volume": "127",
  "bypass_wm": "0",
  "cspot_config": "{\"deviceName\":\"squeezelite-aea06c\",\"bitrate\":160}",
  "dac_config": "",
  "dac_controlset": "",
  "dhcp_tmout": "8",
  "display_config": "",
  "enable_airplay": "1",
  "enable_bt_sink": "1",
  "enable_cspot": "1",
  "equalizer": "",
  "eth_config": "",
  "ethtmout": "8",
  "gpio_exp_config": "",
  "host_name": "squeezelite-aea06c",
  "i2c_config": "",
  "jack_mutes_amp": "n",
  "led_brightness": "",
  "led_vu_config": "",
  "lms_ctrls_raw": "n",
  "loudness": "0",
  "metadata_config": "",
  "model_config": "",
  "ota_erase_blk": "249856",
  "ota_prio": "6",
  "ota_stack": "10240",
  "pollmin": "15",
  "pollmx": "600",
  "rel_api": "https://api.github.com/repos/sle118/squeezelite-esp32/releases",
  "release_url": "CONFIG_SQUEEZELITE_ESP32_RELEASE_URL",
  "rotary_config": "",
  "set_GPIO": "",
  "sleep_config": "",
  "spdif_config": "",
  "spi_config": "",
  "stats": "n",
  "target": "",
  "telnet_block": "500",
  "telnet_buffer": "40000",
  "telnet_enable": ""
}
</code></pre>
</details>

### Logs

To share logs:

1. Connect your player to a computer using a USB cable. Use a built-in Serial-USB adapter if your player has one, or an external USB adapter otherwise.
2. Go to the [web installer](https://sle118.github.io/squeezelite-esp32-installer/).
3. Click "Connect to Device".
4. Select the appropriate serial port.
5. Click "Logs And Console".
6. Download the logs and share them here. Please remove any sensitive information like Wi-Fi passwords or MAC addresses.
- **If the problem occurs soon after booting**: Share the full log until the issue occurs.
- **If the problem occurs later during playback**: Trim the logs to include information just before and after the problem occurs.

#### Example Log

Here's an example log for reference. Make sure to obfuscate sensitive information like Wi-Fi passwords, MAC addresses, and change IP addresses to something more generic.

<details>
<pre><code>
=== START OF LOG ===
I (1191) esp_app_main: Starting app_main
I (1201) nvs_utilities: Initializing flash nvs 
I (1211) nvs_utilities: Initializing nvs partition settings
I (1261) esp_app_main: Setting up telnet.
I (1261) telnet: Telnet support disabled
I (1271) esp_app_main: Setting up config subsystem.
W (1331) nvs_utilities: Configuration memory usage.  Heap internal:262927 (min:262551) (used:15144) external:4152147 (min:4144727) (used:0)
I (1341) esp_app_main: Registering default values
I (1341) system_api: Base MAC address is not set
I (1351) system_api: read default base MAC address from EFUSE
W (1361) config: Waiting for config commit ...
I (2341) config: configuration has some uncommitted entries
I (2341) config: Committing configuration to nvs. Locking config object.
I (2341) config: Done Committing configuration to nvs.
I (2341) config: Config committed!
I (2351) esp_app_main: Configuring services
I (2351) services: Configuring I2C sda:-1 scl:-1 port:1 speed:400000
W (2361) services: no I2C configured
I (2361) services: Configuring SPI mosi:-1 miso:-1 clk:-1 host:1 dc:-1
W (2371) services: no SPI configured
W (2381) led: LED GPIO -1 ignored
W (2381) led: LED GPIO -1 ignored
I (2381) led: Configuring LEDs green:-1 (on:0 rmt:-1 -1% ), red:-1 (on:0 rmt:-1 -1% )
I (2391) battery: No battery
I (2401) monitor: Initializing monitoring
I (2401) monitor: Heap internal:263415 (min:262523) external:4135811 (min:4135795) dma:217067 (min:216191)
I (2411) esp_app_main: Initializing display
I (2421) display: Trying to configure display with N/A
W (2421) display: No display driver
I (2431) esp_app_main: Initializing led_vu
I (2431) led_vu: led_vu configuration invalid
I (2431) esp_app_main: Checking for update url
W (2441) config: Value not found for key fwurl
0;33mW (2461) config: Value not found for key apdelay
I (2461) uart: queue free spaces: 3
I (2461) network_handlers: Network manager configuration: polling max 10176, polling min 15000, ap delay 20000, dhcp timeout 8000, eth timeout 8000
W (2481) network_wifi: No known access point found
E (2481) nvs_utilities: Could not open the nvs storage.
W (2491) network_wifi: network manager has no previous configuration. ESP_FAIL
I (2491) http_server: Initializing HTTP Server
I (2511) network_handlers: Running recovery. Skipping ethernet, starting WiFi
I (2521) wifi:wifi driver task: 3ffc969c, prio:23, stack:6656, core=0
I (2521) wifi:wifi firmware version: 9ec65ef
I (2521) wifi:wifi certification version: v7.0
I (2521) wifi:config NVS flash: enabled
I (2531) wifi:config nano formating: disabled
I (2531) wifi:Init data frame dynamic rx buffer num: 40
I (2531) wifi:Init management frame dynamic rx buffer num: 40
I (2541) wifi:Init management short buffer num: 32
I (2541) wifi:Init static tx buffer num: 12
I (2551) wifi:Init tx cache buffer num: 32
I (2551) wifi:Init static rx buffer size: 1600
I (2561) wifi:Init static rx buffer num: 12
I (2571) wifi:Init dynamic rx buffer num: 40
I (2571) wifi_init: tcpip mbox: 32
I (2571) wifi_init: udp mbox: 32
I (2571) wifi_init: tcp mbox: 32
I (2581) wifi_init: tcp tx win: 8192
I (2581) wifi_init: tcp rx win: 32768
I (2591) wifi_init: tcp mss: 1440
I (2591) wifi_init: WiFi/LWIP prefer SPIRAM
I (2591) network_wifi: Starting wifi
I (2601) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (2691) wifi:mode : sta (a8:42:e3:ae:a0:6c)
I (2691) wifi:enable tsf

W (2691) network_handlers: No saved wifi. Starting AP configuration mode.
I (2691) network_wifi: Configuring Access Point.
I (2711) network: Stopping DHCP server
I (2711) network: Starting DHCP server
I (2721) network_wifi: AP SSID: squeezelite-aea06c
I (2721) network_wifi: AP Password: squeezelite
I (2731) wifi:mode : sta (a8:42:e3:ae:a0:6c) + softAP (a8:42:e3:ae:a0:6d)
I (2731) wifi:Total power save buffer number: 6
I (2731) wifi:Init max length of beacon: 752/752
I (2741) wifi:Init max length of beacon: 752/752
****************************************************************
RECOVERY APPLICATION
This mode is used to flash Squeezelite into the OTA partition
****

I (3271) wifi:Total power save buffer number: 6
I (3291) wifi:Total power save buffer number: 6
I (3291) wifi:Set ps type: 1

I (3291) network_wifi: Initiating wifi network scan
I (3291) dns_server: DNS Server listening on 53/udp
Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.

****************************
Your terminal application does not support escape sequences.
Line editing and history features are disabled.
On Windows, try using Putty instead.
****************************
recovery-squeezelite-esp32>I (32801) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (32801) wifi:station: da:77:e0:a1:91:c3 join, AID=1, bgn, 20
I (33251) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.4.2
W (33591) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
W (34191) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
E (34311) httpd_handlers: resource_filehandler(399): Unknown resource [favicon.ico] from path [/favicon.ico] 
W (34311) httpd_txrx: httpd_resp_send_err: 404 Not Found - File does not exist
W (34341) httpd_uri: httpd_uri: uri handler execution failed
W (34401) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
W (34531) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
I (34651) httpd_handlers: serving / to peer 192.168.4.2 port 49321
I (35191) httpd_handlers: serving /config.json to peer 192.168.4.2 port 49833
I (35391) httpd_handlers: serving /commands.json to peer 192.168.4.2 port 58537
W (35391) config: Adding new config value for key [model_config]
W (35401) config: Adding new config value for key [a2dp_spin]
I (36341) config: configuration has some uncommitted entries
I (36341) config: Committing configuration to nvs. Locking config object.
I (36361) nvs_utilities: Value stored under key 'model_config'
I (36361) nvs_utilities: Value stored under key 'a2dp_spin'
I (36361) config: Done Committing configuration to nvs.
I (36721) network_wifi: Initiating wifi network scan
W (38571) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
W (41481) httpd_handlers: redirect_processor(1002): 192.168.4.2 requested invalid URL: [/gen_204]
W (41501) httpd_handlers: process_redirect(957): Redirecting host [192.168.4.2] to http://192.168.4.1/ (from uri /gen_204)
W (41671) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
I (49391) network: Starting DHCP client
I (49391) network_wifi: Wifi Connecting to FRITZ!Box 7590 JV...
I (52221) wifi:primary chan differ, old=1, new=6, start CSA timer
I (52621) wifi:switch to channel 6
I (52621) wifi:ap channel adjust o:1,0 n:6,0
I (52621) wifi:new:<6,0>, old:<1,0>, ap:<6,0>, sta:<0,0>, prof:1
I (52621) wifi:new:<6,0>, old:<6,0>, ap:<6,0>, sta:<6,0>, prof:1
I (53161) wifi:state: init -> auth (b0)
I (53171) wifi:state: auth -> assoc (0)
I (53171) wifi:state: assoc -> run (10)
I (53201) wifi:connected with FRITZ!Box 7590 JV, aid = 1, channel 6, BW20, bssid = 74:42:7f:3f:ff:09
I (53201) wifi:security: WPA2-PSK, phy: bgn, rssi: -76
I (53221) wifi:pm start, type: 1

I (53221) network_handlers: Wifi was connected. Waiting for IP address
I (53241) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (54221) network: Got an IP address from interface Wifi. IP=192.168.178.162, Gateway=192.168.178.1, NetMask=255.255.255.0, Address was changed
I (54231) esp_netif_handlers: sta ip: 192.168.178.162, mask: 255.255.255.0, gw: 192.168.178.1
E (54231) nvs_utilities: Could not open the nvs storage.
I (54241) network_wifi: SSID FRITZ!Box 7590 JV was changed or is new. Committing to flash
E (54251) messaging: FRITZ!Box 7590 JV (config). Error ESP_ERR_NVS_KEY_TOO_LONG
I (54261) network_wifi: Committing active access point
I (54271) nvs_utilities: Value stored under key 'ssid'
I (54271) nvs_utilities: Value stored under key 'password'
W (56141) httpd_txrx: httpd_sock_err: error in send : 104
W (56141) httpd_txrx: httpd_sock_err: error in recv : 104
I (63821) httpd_handlers: serving /config.json to peer 192.168.4.2 port 37023
I (64011) httpd_handlers: serving /commands.json to peer 192.168.4.2 port 45727
W (64471) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
W (64591) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
I (65331) network_wifi: Initiating wifi network scan
W (73151) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
I (73481) httpd_handlers: serving /messages.json to peer 192.168.4.2 port 64728
W (74351) httpd_handlers: process_redirect(964): Responding to host [192.168.4.2] (from uri /generate_204) with redirect html page <html><head><title>Redirecting to Captive Portal</title><meta http-equiv='refresh' content='0; url=http://192.168.4.1'></head><body><p>Please wait, refreshing.  If page does not refresh, click <a href='http://192.168.4.1'>here</a> to login.</p></body></html>
W (74421) httpd_txrx: httpd_sock_err: error in recv : 104
I (74731) network_wifi: Initiating wifi network scan
I (77571) httpd_handlers: serving /ap.json to peer 192.168.4.2 port 2265
W (77711) httpd_txrx: httpd_sock_err: error in send : 104
W (77711) httpd_txrx: httpd_sock_err: error in recv : 104
I (98031) wifi:station: da:77:e0:a1:91:c3 leave, AID = 1, bss_flags is 655475, bss:0x3f8261d8
I (98031) wifi:new:<6,0>, old:<6,0>, ap:<6,0>, sta:<6,0>, prof:1
I (111141) wifi:mode : sta (a8:42:e3:ae:a0:6c)
I (111141) network_wifi: Starting wifi
I (111141) esp_app_main: Network connected and mDNS initialized with squeezelite-aea06c
I (111151) squeezelite-ota: sending LMS discovery for OTA Update
I (111261) squeezelite-ota: got response from: 192.168.178.190:3483 - EJSON9000CLIP9090
I (111261) network_status: LMS IP: 192.168.178.190, hport: 9000, cport: 9090
I (111281) esp_app_main: Network connected and mDNS initialized with squeezelite-aea06c
I (111291) squeezelite-ota: sending LMS discovery for OTA Update
I (111351) squeezelite-ota: got response from: 192.168.178.190:3483 - EJSON9000CLIP9090
I (111351) network_status: LMS IP: 192.168.178.190, hport: 9000, cport: 9090
I (1430801) httpd_handlers: serving / to peer 192.168.178.199 port 23256
I (1431311) httpd_handlers: serving /config.json to peer 192.168.178.199 port 24280
I (1431371) httpd_handlers: serving /commands.json to peer 192.168.178.199 port 30424
I (1432831) network_wifi: Initiating wifi network scan
W (1435691) httpd_txrx: httpd_sock_err: error in send : 104
W (1435691) httpd_txrx: httpd_sock_err: error in recv : 104
I (1435741) httpd_handlers: serving /messages.json to peer 192.168.178.199 port 33496
=== END OF LOG ===   
</code></pre>
</details>

### Issue Description

1. **Observed Behavior**: I think there is no response from LMS
2. **Expected Behavior**: I assume there should be a response from LMS like in other logs that I have seen from other people.
3. **Steps to Reproduce**: Install squeezelite onto ESP32-WROVER-IB--> connect to Wifi --> try to configure settings or wait that it is found by LMS and discoverble by bluetooth and Airplay ect.

**Comment by sle118** [comment]
You are in recovery mode, likely. 

Open the web interface and you should see a button at the bottom to exit this mode which comes by default.

Let us know how that goes

**Comment by Charliestonedassgueniapig** [comment]
> You are in recovery mode, likely.
> 
> Open the web interface and you should see a button at the bottom to exit this mode which comes by default.
> 
> Let us know how that goes

Thank you for your help! It worked and now I can use my ESP like intended. Pardon me if this problem was to rash but I have not seen any suggestion to such a step anywhere (maybe I had overlooked something).

**Comment by sle118** [comment]
> > You are in recovery mode, likely.
> > Open the web interface and you should see a button at the bottom to exit this mode which comes by default.
> > Let us know how that goes
> 
> Thank you for your help! It worked and now I can use my ESP like intended. Pardon me if this problem was to rash but I have not seen any suggestion to such a step anywhere (maybe I had overlooked something).

Enjoy!
