### ISSUE TITLE
development.108-I2S-4MFlash loses WiFi

### ISSUE THREAD

**Issue by ElFishi** [sle118/squeezelite-esp32#47]
My esp frequently loses the WiFi connection: 
Sound stops, display freezes, and web interface is not available.  
I can issue a restart command via the serial interface and the WiFi connects w/o problems. LMS shows the player with a signal stregth of 73%.

log file attached.
[wifi lost scarlet 200828.txt](https://github.com/sle118/squeezelite-esp32/files/5143933/wifi.lost.scarlet.200828.txt)

**Comment by philippe44** [comment]
Can you try to reset your router? I did not change anything wrt WiFi recently and I've send once or twice the same thing happening to me and everytime it was because something went south in my router

**Comment by kheperV3** [comment]
Maybe it's a SPIFFS problem (WiFi needs it...)
Try to reformat...

**Comment by sle118** [comment]
@philippe44 we did change a config earlier this year, but it was to resolve an issue. Is it possible that new config options were added in idf V4?

**Comment by philippe44** [comment]
Does it still happen?

**Comment by ElFishi** [comment]
hasn't for a while now.
