### ISSUE TITLE
After boot, green led is left blinking quickly by WiFi

### ISSUE THREAD

**Issue by philippe44** [sle118/squeezelite-esp32#50]
I've fixed that in make version but cmake has some changes that I don't know. After boot, when the network is acquired, the green led status is not restored. I guess an event is not caught that happens upon getting an IP address

**Comment by sle118** [comment]
The following message is correctly received when the WiFi connection is established.  
![image](https://user-images.githubusercontent.com/5656564/91873505-18bb9080-ec47-11ea-93f2-7c408d392636.png)
Following this, a call is made to "led_unpush" and no indication of a failure.

**Comment by sle118** [comment]
fix pushed. Tested successfully.
