### ISSUE TITLE
Feature request: MQTT

### ISSUE THREAD

**Issue by timotoots** [sle118/squeezelite-esp32#54]
It seems this firmware is a stable media player for ESP32.

I was looking for something to be used just as a smart speaker without the Logitech media player. That you could control from Home Assistant or any MQTT enabled system.

Could it be possible to extend this to be a standalone player with MQTT or HTTP controls? It would be great to use it as general purpose audio player. If you could point an media URL to this device, it would allow using any media server as a music repository.

**Comment by sle118** [comment]
Someone is working on a port of Spotify, which I'm hoping will be integrated in the upcoming weeks.

Given that the whole point of the system was to work in the Logitech media server ecosystem, and given that we are getting close to the storage space limits, I doubt implementing this will be possible.
