### ISSUE TITLE
unnecessary dependencies

### ISSUE THREAD

**Issue by philippe44** [sle118/squeezelite-esp32#59]
https://github.com/sle118/squeezelite-esp32/blob/2687023b6fec54802694b10ba0ebbba8ebc5eb15/components/services/monitor.c#L151

I don't feel good about that being here. I think it's really important we try to keep items layered and independents and I'm afraid we are creating too many intricacies/entanglements, including the UI finding its way into operational code.

**Comment by sle118** [comment]
Agreed. I have removed all references of this from all other components. The status update will now be initiated by the http status handler, which is where it actually belongs. I also removed the "jack inserted/removed message" for now. There isn't much use for this, especially given that the UI already has an icon to represent current jack status.
