### ISSUE TITLE
A1S 526/529: wifi disconnects, slimproto_run 602 errors, BT_APPL underflow error causing skip to next track

### ISSUE THREAD

**Issue by KeBul** [sle118/squeezelite-esp32#62]
Initially thought these were just occurring when connected to a Bluetooth sink but it also occurred when configured for I2S and using wired headphones plugged in the headphone jack.
Basically when playing through a playlist (local VBR MP3s), pretty much every track fails to complete, playback skipping to the next track at any any seemingly random time.
The console logs shows these are caused by wifi disconnects/slimproto disconnects and underflow errs - not an expert but would guess the wifi disconnect is the cause of the others 
For me this behaviour is unique to 526/529, I've used 142 for many hours at a time with no skips, but get this behaviour as soon as I upgrade to 526 or 529, upgrade can be a re-flash from scratch after flash erase using ESP32 download tool or OTA upgrade from v142
It makes 526/529 unusable for me.

If I OTA downgrade to 142, let it complete and reboot, no other changes, then playback is perfect with no wifi disconnects

A couple of console logs:

[wifidropsandbrokenplayandskips.txt](https://github.com/sle118/squeezelite-esp32/files/5580492/wifidropsandbrokenplayandskips.txt)

[wifilostskippingtracks2.txt](https://github.com/sle118/squeezelite-esp32/files/5580501/wifilostskippingtracks2.txt)

Update... Further testing in response to Sebastien's query regarding GPIO clashes, I've erased and reflashed an A1S to 526 using the ESP download tool, connected it to my wifi, and started using it with wired headphones, no other changes were made, so default settings from the flash process. Below is the nvm text file:

[nvs_config1606211170053json.txt](https://github.com/sle118/squeezelite-esp32/files/5588939/nvs_config1606211170053json.txt)

The wifi drops and subsequent skips to next track continued as previously experienced. 
As wifi mode is set by default to power save (f) the device was connected to my access point on channel 1 (AP furthest away) I then changed the wifi mode in nvm to comprehensive (a) saved and rebooted, confirmed device was connected to the nearest AP and re-tested... and am still getting the wifi drops.

**Comment by sle118** [comment]
We discovered that there was an issue with the ESP-IDF release used during the GitHub build process. It was updated starting on build number 546. Please test again and report if the situation improved.

**Comment by philippe44** [comment]
Can we close this one?

**Comment by KeBul** [comment]
Hi Guys,

I've been testing on Version 552 and can confirm I'm no longer seeing this issue.

Thanks for your time and effort to resolve, I'm happy for you to close this now.
