### ISSUE TITLE
A1S_542: You have to select Bit Depth without the need of it.

### ISSUE THREAD

**Issue by Harry-1999** [sle118/squeezelite-esp32#66]
If you save a non SSD1326-display, the hardware/display-section asks you to set the Bit Depth.
You only should set this, if you realy want to use a SSD1326-display.

(my) saved result in NVS-Editor: (with selected "1" for BitDepth, otherwise i can't save it)
SPI:width=128,height=64,cs=12,reset=22,speed=8000000,driver=SSD1306,HFlip,VFlip

If you need the 1 even with other displays than SSD1326, then the default should be "1", not "---".

**Comment by sle118** [comment]
The UI frontend is very generic and doesn't perform validation outside of predefined values for drop down, this is a backend change.

The system should actually allow '--' as a valid value that is not saved, only for drivers other than SSD1326.

**Comment by Harry-1999** [comment]
<img width="271" alt="fehler" src="https://user-images.githubusercontent.com/77048420/104095509-7caa3180-5297-11eb-997b-0413fe79193a.PNG">

**Comment by sle118** [comment]
The system "should" but doesn't, thus this problem. ;)

**Comment by sle118** [comment]
This is now resolved on my development system.

**Comment by sle118** [comment]
Note:  since the parameter was defined in the backend as integer, the issue was addressed on the front end.  There was a bug in the command line construction logic which incorrectly included drop down default values. The logic was updated to generate a command line that only contains valid values.

**Comment by sle118** [comment]
Please test the latest release and reopen of necessary. https://github.com/sle118/squeezelite-esp32/commit/5120029643f5f4fa8f64a542e4a5e0ef68859c0d should fix the issue
