### ISSUE TITLE
reboots when bluetooth is on

### ISSUE THREAD

**Issue by Mum-Pf** [sle118/squeezelite-esp32#67]
Hi
I‘ve sometimes a unintentionally and not reproducible reboot of my board. It looks, that the board works without reboot, if I turn off the bluetooth in this section:

![Bluetooth](https://user-images.githubusercontent.com/77235475/104125194-88f4c400-5355-11eb-8f3c-75b36741dcbd.jpg)

I've a AI-Thinker-ESP32AudioKit-V2.2 and nothing in jack, only 2 speekers on amp, a rotary controller 3 buttons and a I2C display.

And I‘ve several devices paired with this board (Smartphone, Tablet, PC) and it could be, that they connect this board in background, while it plays a radio-stream.

I disable bluetooth and it plays many hours without rebooting, when I enable bluetooth it reboots sometimes after 5 min., sometimes after 1 h.

Here the NVS-config:
[nvs_config_ESP32-squeezelite_1610287831106json.txt](https://github.com/sle118/squeezelite-esp32/files/5792703/nvs_config_ESP32-squeezelite_1610287831106json.txt)

Tested version with this bug: V542 and V546 (other may also have it... not tested)

Many thanks.
M.P.

**Comment by Mum-Pf** [comment]
I may have found the cause of this issue #67:
The problem is: With an active "bluetooth speaker", and no jack (only 2 speaker on the native board AI-Thinker-ESP32AudioKit-V2.2 and NVS: "set_GPIO"="21=amp,39=jack:0"), it reboots sometimes after ~1h. I disable bluetooth and it plays many hours without rebooting.

My guess:
With active bluetooth, I saw in the log, that there were a lot of messages from the 'jack insertion handler' (one line every second):
`...`
`[00:10:35.194078] jack_handler:153 switching amplifier ON`
`[00:10:36.074097] jack_handler:153 switching amplifier ON`
`[00:10:36.484131] jack_handler:153 switching amplifier ON`
`[00:10:37.964359] jack_handler:153 switching amplifier ON`
`[00:10:39.385728] jack_handler:153 switching amplifier ON`
`[00:10:43.244300] jack_handler:153 switching amplifier ON`
`[00:10:44.064113] jack_handler:153 switching amplifier ON`
`[00:10:45.964427] jack_handler:153 switching amplifier ON`
`[00:10:48.054128] jack_handler:153 switching amplifier ON`
`[00:10:49.694138] jack_handler:153 switching amplifier ON`
`[00:10:50.326820] jack_handler:153 switching amplifier ON`
`[00:10:53.684107] jack_handler:153 switching amplifier ON`
`[00:10:54.254113] jack_handler:153 switching amplifier ON`
`[00:10:55.634917] jack_handler:153 switching amplifier ON`
`[00:10:55.884107] jack_handler:153 switching amplifier ON`
`[00:10:58.094091] jack_handler:153 switching amplifier ON`
`[00:11:06.318808] jack_handler:153 switching amplifier ON`
`[00:11:06.565375] jack_handler:153 switching amplifier ON`
`[00:11:07.964348] jack_handler:153 switching amplifier ON`
`[00:11:12.314145] jack_handler:153 switching amplifier ON`
`[00:11:13.234117] jack_handler:153 switching amplifier ON`
`[00:11:14.314147] jack_handler:153 switching amplifier ON`
`[00:11:20.006296] jack_handler:153 switching amplifier ON`
`[00:11:20.414082] jack_handler:153 switching amplifier ON`
`[00:11:20.664207] jack_handler:153 switching amplifier ON`
`[00:11:22.854116] jack_handler:153 switching amplifier ON`
`[00:11:23.104093] jack_handler:153 switching amplifier ON`
`[00:11:23.994172] jack_handler:153 switching amplifier ON`
`[00:11:24.404088] jack_handler:153 switching amplifier ON`
`[00:11:24.814125] jack_handler:153 switching amplifier ON`
`...`

without bluetooth it logs much less (only one line every 26 sec.):

`...`
`[00:14:38.417702] jack_handler:153 switching amplifier ON`
`[00:15:14.102494] jack_handler:153 switching amplifier ON`
`[00:16:11.455618] jack_handler:153 switching amplifier ON`
`....`

Maybe the reason for the reboots is a memory problem caused by logging.
So, I deactivated the logging in 

> components\squeezelite\output_i2s.c (line 153)
> `// LOG_INFO("switching amplifier %s", inserted ? "OFF" : "ON");`

compiled it, flashed it and the board no longer reboots.

My code based on v634.

Could that be the problem? Is it normal, that the 'jack insertion handler' in output_i2s.c logs so much, when enable bluetooth?

Many thanks.
M.P.

**Comment by philippe44** [comment]
oh, this one... it's likely an issue with wifi powersave that is needed when gpio 36 or 39 are used. I just look ed at the code but @sle118 commented out that code and I have to ask him why

**Comment by robho** [comment]
> I've a AI-Thinker-ESP32AudioKit-V2.2 and nothing in jack, only 2 speekers on amp, a rotary controller 3 buttons and a I2C display.

In this case, since you're not using the headphone jack I think you can just remove "39=jack:0" from set_GPIO and set audio output to "Subwoofer" under "General Audio Options" in the web UI.

**Comment by philippe44** [comment]
I've moved gpio 36 & 39 to polling mode
