### ISSUE TITLE
Link to install instructions for non-Squeezeamp hardware

### ISSUE THREAD

**Issue by troffasky** [sle118/squeezelite-esp32#69]
A link somewhere on the main page to install instructions for non-Squeezeamp hardware would be useful. I found them in the first post here:
https://forums.slimdevices.com/showthread.php?112697-ANNOUNCE-Squeezelite-ESP32-(dedicated-thread)

Also, "esptool" is in Debian and Ubuntu repos so "apt install esptool" helped to get me going on an ESP32-A1S dev board.

**Comment by philippe44** [comment]
Done
