### ISSUE TITLE
Plugin can't be installed due to checksum missmatch

### ISSUE THREAD

**Issue by Phil1pp** [sle118/squeezelite-esp32#72]
Slim::Utils::PluginDownloader::_installDownload (210) digest does not match /config/cache/DownloadedPlugins/SqueezeESP32.zip - SqueezeESP32 will not be installed: expected ab2d65f5ba8e73f0f78a1a8650af19ebb1e8e724, got c33af63de1c2e799a05352708b9f5db9e8d1102a

**Comment by philippe44** [comment]
I think that has been corrected
