### ISSUE TITLE
[Enhancement] Add multiroom support for Chromecast Audio / Spotify Connect

### ISSUE THREAD

**Issue by matebuteler** [sle118/squeezelite-esp32#77]
Thank you! I think that would really improve the project.

**Comment by philippe44** [comment]
Chromecast is not possible

**Comment by sle118** [comment]
As for Spotify, it is definitely something that we are considering. I'll go ahead and close this for now.

thank you!

**Comment by philippe44** [comment]
Here I would disagree - contrary to Spotify, this is something I do not consider. The runtime, security model & codebase of CC make it impossible from a size, CPU and licensing point of view.
