### ISSUE TITLE
Preset-Buttons don't work... solution found

### ISSUE THREAD

**Issue by Mum-Pf** [sle118/squeezelite-esp32#79]
Hi
the new preset-buttons from PR#64 have a litle typo-bug... you forgot a "_"-char (underscore).
File components/squeezelite/controls.c
Line 145 – 150
old: LMS_CALLBACK(pre1, PRESET_1, preset1.single)
new : LMS_CALLBACK(pre1, PRESET_1, preset_1.single)
...
old: LMS_CALLBACK(pre6, PRESET_6, preset6.single)
new: LMS_CALLBACK(pre6, PRESET_6, preset_6.single)

I compiled the new lines and it worked :-)
Can you integrate it to your next version?

Many greetings and thank you
M.P.

**Comment by sle118** [comment]
Please check and close the issue if it works

**Comment by Harry-1999** [comment]
I tested ist... and now it works... 570:A1S
Presets and Power

**Comment by Mum-Pf** [comment]
thanks, it works with v570 (A1S)
