### ISSUE TITLE
Player name is not saved permanent

### ISSUE THREAD

**Issue by networxnet** [sle118/squeezelite-esp32#82]
Player name is not saved permanent after change.
Name will reset to squeezelite-fbeXXX after every reboot.

**Comment by networxnet** [comment]
Same prob with latest firmware, LMS 8.2.0

**Comment by shaffenmeister** [comment]
### Where do you change the player's name?
1. On the player's own web UI --> Changing the name does work for me.
2. Changing the name via LMS --> Name is lost after reboot, as per your observation

### Observed behaviour on SqueezeliteESP32
Serial output after issuing the "change name command" via LMS web UI:
`[00:42:08.033724] process_setd:480 set name: SqueezeESP32b`

I.e. the command is sent to the client correctly, the client does not issue an error message.

### Environment:
* Logitech Media Server Version: 8.1.2 - 1616822325 @ Sat Mar 27 06:39:42 CET 2021
* fw: SqueezeAmp.16.629.master-cmake, mode: squeezelite

**Comment by networxnet** [comment]
Changing from LMS ist not permanent (why?).

Changing from Players UI will have no effect on LMS.

![Screenshot_20210328-131414](https://user-images.githubusercontent.com/16120065/112750281-0da3c580-8fc8-11eb-8a9d-82a4573b6cb4.png)
![Screenshot_20210328-131525](https://user-images.githubusercontent.com/16120065/112750287-15636a00-8fc8-11eb-8c71-50d68670dff9.png)

**Comment by networxnet** [comment]
After rewrite 629-16 firmware and change name from players ui to another value, save and change Back, it seems to work.

Open question: Why it does not work from LMS like other players?

**Comment by philippe44** [comment]
It's because the SETD command is not honored by squeezelite-esp32. I would have to add modifications to the "stock" squeezelite. This is not much more a "stock" version now, so I'll do that in the coming days.

**Comment by philippe44** [comment]
Done
