### ISSUE TITLE
Fail to update dev.634-16#v4.0#I2S-4MFlash#master-cmake

### ISSUE THREAD

**Issue by networxnet** [sle118/squeezelite-esp32#87]
OTA: 

Squeezelite boot to recovery. Log: Save Success

Starting from Recovery:
Error: Failed to execute HTTP download. ERROR

Sometimes it generates log entry:
Unable to retrieve HTTPS certificates. Memory allocation failed

Manual upload:

Log: File uploaded. Flashing started. 
After this nothing happens.

Sometimes: 400 Error! Binary file too large. Unable to allocate memory!

**Comment by sle118** [comment]
There is a known issue with the TLS certificates and we are working on a permanent fix (see  #85 ). In the meantime, please use the following like to find binaries images with recent certificates. These should restore firmware update capabilities.  https://forums.slimdevices.com/showthread.php?112697-ANNOUNCE-Squeezelite-ESP32-(dedicated-thread)&p=983839&viewfull=1#post983839
