### ISSUE TITLE
Compile error with IDFv4.0

### ISSUE THREAD

**Issue by rsm123** [sle118/squeezelite-esp32#97]
I'm getting compile error on manual install.

/Users/rsm/esp/esp-idf-v4.0/squeezelite-esp32/components/platform_config/platform_config.c: In function 'malloc_fn':
/Users/rsm/esp/esp-idf-v4.0/squeezelite-esp32/components/platform_config/platform_config.c:75:15: error: 'is_recovery_running' undeclared (first use in this function)
  void * ptr = is_recovery_running?malloc(sz):heap_caps_malloc(sz, MALLOC_CAP_SPIRAM);
               ^~~~~~~~~~~~~~~~~~~
/Users/rsm/esp/esp-idf-v4.0/squeezelite-esp32/components/platform_config/platform_config.c:75:15: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [platform_config.o] Error 1
make: *** [component-platform_config-build] Error 2

I'd appreciate any help to resolve this.

**Comment by rsm123** [comment]
issue got resolved

**Comment by MichaelPNolan** [comment]
i have this problem ... would like to know

**Comment by rsm123** [comment]
> i have this problem ... would like to know

Don't remember, i think I selected previous IDF version.

**Comment by MichaelPNolan** [comment]
Thanks - yes, that's often a big part of it.
